import type { Exercicio } from '../types/treino';

export const EXERCICIOS_PADRAO: Exercicio[] = [

  // ─── PEITO ───────────────────────────────────────────────────────────────
  {
    id: 1001, nome: 'Supino Reto com Barra', grupoMuscular: 'Peito',
    musculosSecundarios: 'Tríceps, Ombros',
    equipamento: 'Barra, Banco',
    descricao: '1. Deite no banco com os pés apoiados no chão.\n2. Segure a barra com pegada um pouco mais larga que os ombros.\n3. Desça a barra controlando até tocar levemente o peito.\n4. Empurre a barra para cima até os braços ficarem quase estendidos.\n5. Mantenha as escápulas retraídas e o core contraído durante todo o movimento.',
  },
  {
    id: 1002, nome: 'Supino Inclinado com Barra', grupoMuscular: 'Peito',
    musculosSecundarios: 'Tríceps, Ombros',
    equipamento: 'Barra, Banco inclinado',
    descricao: '1. Ajuste o banco a 30–45°.\n2. Segure a barra com pegada larga e desça até a parte superior do peito.\n3. Empurre para cima sem trancar os cotovelos.\n4. Foco na porção superior do peitoral.',
  },
  {
    id: 1003, nome: 'Supino Declinado com Barra', grupoMuscular: 'Peito',
    musculosSecundarios: 'Tríceps',
    equipamento: 'Barra, Banco declinado',
    descricao: '1. Prenda os pés no suporte do banco declinado.\n2. Segure a barra com pegada larga.\n3. Desça a barra até a parte inferior do peito.\n4. Empurre para cima de forma controlada.\n5. Trabalha a porção inferior do peitoral.',
  },
  {
    id: 1004, nome: 'Supino Reto com Halteres', grupoMuscular: 'Peito',
    musculosSecundarios: 'Tríceps, Ombros',
    equipamento: 'Halteres, Banco',
    descricao: '1. Segure um halter em cada mão e deite no banco.\n2. Inicie com os halteres na altura do peito, cotovelos a 45°.\n3. Estenda os braços para cima sem trancá-los.\n4. Retorne de forma controlada, abrindo o peito.\n5. Amplitude maior que o supino com barra.',
  },
  {
    id: 1005, nome: 'Supino Inclinado com Halteres', grupoMuscular: 'Peito',
    musculosSecundarios: 'Ombros, Tríceps',
    equipamento: 'Halteres, Banco inclinado',
    descricao: '1. Ajuste o banco a 30–45°.\n2. Segure um halter em cada mão na altura do peito superior.\n3. Empurre para cima convergindo os halteres levemente.\n4. Desça de forma controlada sentindo o estiramento do peito.',
  },
  {
    id: 1006, nome: 'Crucifixo Reto com Halteres', grupoMuscular: 'Peito',
    musculosSecundarios: 'Ombros',
    equipamento: 'Halteres, Banco',
    descricao: '1. Deite no banco segurando halteres acima do peito, palmas se encarando.\n2. Abra os braços em arco para os lados até sentir o peito esticar.\n3. Mantenha leve flexão nos cotovelos durante todo o movimento.\n4. Retorne os halteres para cima fechando o arco.',
  },
  {
    id: 1007, nome: 'Crucifixo Inclinado com Halteres', grupoMuscular: 'Peito',
    musculosSecundarios: 'Ombros',
    equipamento: 'Halteres, Banco inclinado',
    descricao: '1. Banco a 30–45°.\n2. Execute o movimento de crucifixo focando na porção superior do peitoral.\n3. Controle a descida sentindo o estiramento.\n4. Feche o arco no topo espremendo o peito.',
  },
  {
    id: 1008, nome: 'Crossover no Cabo', grupoMuscular: 'Peito',
    musculosSecundarios: 'Ombros',
    equipamento: 'Cabo cruzado',
    descricao: '1. Ajuste as polias na altura dos ombros ou acima.\n2. Fique no centro e segure as alças com os braços abertos.\n3. Puxe as alças em arco, cruzando as mãos na frente do corpo.\n4. Esprema o peito no ponto de cruzamento.\n5. Retorne controlando a abertura.',
  },
  {
    id: 1009, nome: 'Pec Deck (Voador)', grupoMuscular: 'Peito',
    musculosSecundarios: 'Ombros',
    equipamento: 'Máquina',
    descricao: '1. Ajuste o assento para que os cotovelos fiquem na altura dos ombros.\n2. Apoie os antebraços nas almofadas ou segure as alças.\n3. Feche os braços à frente do corpo espremendo o peito.\n4. Retorne de forma controlada sem deixar o peso bater.',
  },
  {
    id: 1010, nome: 'Flexão de Braço', grupoMuscular: 'Peito',
    musculosSecundarios: 'Tríceps, Ombros, Core',
    equipamento: 'Peso corporal',
    descricao: '1. Posição de prancha com mãos levemente mais largas que os ombros.\n2. Desça o corpo mantendo-o reto, cotovelos a 45° do tronco.\n3. Toque levemente o peito ou quase no chão.\n4. Empurre de volta à posição inicial.\n5. Não deixe o quadril cair.',
  },
  {
    id: 1011, nome: 'Mergulho em Paralelas (Peito)', grupoMuscular: 'Peito',
    musculosSecundarios: 'Tríceps, Ombros',
    equipamento: 'Paralelas',
    descricao: '1. Segure as paralelas e suba com os braços estendidos.\n2. Incline o tronco levemente para frente para focar no peito.\n3. Desça dobrando os cotovelos para os lados até sentir o peito esticar.\n4. Empurre de volta sem trancar os cotovelos.',
  },
  {
    id: 1012, nome: 'Pullover com Halter', grupoMuscular: 'Peito',
    musculosSecundarios: 'Costas, Tríceps',
    equipamento: 'Halter, Banco',
    descricao: '1. Deite transversalmente no banco com apenas as escápulas apoiadas.\n2. Segure um halter com as duas mãos acima do peito.\n3. Abaixe o halter em arco atrás da cabeça mantendo leve flexão nos cotovelos.\n4. Retorne para a posição inicial espremendo o peito.',
  },
  {
    id: 1013, nome: 'Supino Declinado com Halteres', grupoMuscular: 'Peito',
    musculosSecundarios: 'Tríceps',
    equipamento: 'Halteres, Banco declinado',
    descricao: '1. Prenda os pés no suporte do banco declinado.\n2. Segure um halter em cada mão na altura do peito inferior.\n3. Empurre para cima sem travar os cotovelos.\n4. Amplitude maior que com barra — explore o estiramento.\n5. Foco na porção inferior do peitoral.',
  },
  {
    id: 1014, nome: 'Crucifixo no Cabo (Polia)', grupoMuscular: 'Peito',
    musculosSecundarios: 'Ombros',
    equipamento: 'Cabo cruzado',
    descricao: '1. Ajuste as polias na altura dos ombros.\n2. Segure as alças com leve flexão nos cotovelos, tronco levemente inclinado.\n3. Feche os braços em arco à frente do corpo, convergindo as mãos.\n4. Esprema o peito no ponto de encontro.\n5. Retorne controlando a abertura. Tensão constante durante todo o movimento.',
  },
  {
    id: 1015, nome: 'Flexão Inclinada (pés elevados)', grupoMuscular: 'Peito',
    musculosSecundarios: 'Tríceps, Ombros',
    equipamento: 'Banco',
    descricao: '1. Apoie os pés em um banco e as mãos no chão.\n2. Corpo inclinado, foco na porção superior do peitoral.\n3. Desça o peito em direção ao chão, cotovelos a 45°.\n4. Empurre de volta à posição inicial.\n5. Quanto mais elevados os pés, maior a ativação do peito superior.',
  },
  {
    id: 1016, nome: 'Flexão de Braço Fechada', grupoMuscular: 'Peito',
    musculosSecundarios: 'Tríceps',
    equipamento: 'Peso corporal',
    descricao: '1. Posição de flexão com as mãos na largura dos ombros ou mais próximas.\n2. Desça mantendo os cotovelos junto ao corpo.\n3. Foco no peito interno e tríceps.\n4. Empurre de volta à posição inicial com controle.',
  },

  // ─── COSTAS ──────────────────────────────────────────────────────────────
  {
    id: 2001, nome: 'Puxada Frontal na Polia', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps, Romboides',
    equipamento: 'Polia alta',
    descricao: '1. Sente na máquina e segure a barra com pegada pronada (larga).\n2. Incline levemente o tronco para trás.\n3. Puxe a barra em direção à parte superior do peito.\n4. Esprema as costas no final do movimento.\n5. Retorne controlando o peso até quase a extensão completa.',
  },
  {
    id: 2002, nome: 'Puxada Pegada Fechada', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps',
    equipamento: 'Polia alta',
    descricao: '1. Use o triângulo ou a barra com pegada neutra próxima.\n2. Mantenha o tronco ereto e puxe em direção ao abdômen superior.\n3. Abra os cotovelos para trás apertando as costas.\n4. Retorne de forma controlada.',
  },
  {
    id: 2003, nome: 'Remada Curvada com Barra', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps, Lombar',
    equipamento: 'Barra',
    descricao: '1. Segure a barra com pegada pronada, tronco inclinado a 45°.\n2. Puxe a barra em direção ao abdômen mantendo as costas retas.\n3. Retraia as escápulas no topo do movimento.\n4. Desça de forma controlada sem deixar os braços pendurar.',
  },
  {
    id: 2004, nome: 'Remada Unilateral com Halter', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps',
    equipamento: 'Halter, Banco',
    descricao: '1. Apoie um joelho e a mão no banco.\n2. Com a outra mão segure o halter com o braço estendido.\n3. Puxe o halter em direção ao quadril, abrindo o cotovelo para trás.\n4. Esprema as costas no topo.\n5. Retorne lentamente até o braço esticar.',
  },
  {
    id: 2005, nome: 'Remada na Polia Baixa', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps, Romboides',
    equipamento: 'Polia baixa',
    descricao: '1. Sente no banco com os pés no apoio e segure o triângulo.\n2. Mantenha as costas eretas e puxe em direção ao abdômen.\n3. Abra os cotovelos para trás, retraindo as escápulas.\n4. Retorne com controle, estirando as costas.',
  },
  {
    id: 2006, nome: 'Remada Cavalinho (T-Bar)', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps, Lombar',
    equipamento: 'Barra T ou máquina',
    descricao: '1. Posicione-se sobre a barra com os pés na largura dos ombros.\n2. Agarre as alças e incline o tronco a ~45°.\n3. Puxe a barra em direção ao peito retraindo bem as escápulas.\n4. Retorne com controle.',
  },
  {
    id: 2007, nome: 'Levantamento Terra', grupoMuscular: 'Costas',
    musculosSecundarios: 'Glúteos, Pernas, Trapézio',
    equipamento: 'Barra',
    descricao: '1. Posicione os pés na largura dos ombros com a barra sobre os pés.\n2. Agache segurando a barra com pegada pronada ou mista.\n3. Peito para fora, lombar neutra, core contraído.\n4. Empurre o chão com os pés e suba, estendendo quadril e joelhos juntos.\n5. Retorne com controle.\n⚠️ Jamais arredonde a lombar.',
  },
  {
    id: 2008, nome: 'Barra Fixa (Pegada Pronada)', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps',
    equipamento: 'Barra fixa',
    descricao: '1. Segure a barra com pegada pronada (palmas para frente), mais larga que os ombros.\n2. Pendure com os braços quase estendidos.\n3. Puxe o corpo para cima até o queixo ultrapassar a barra.\n4. Desça lentamente em 3–4 segundos.',
  },
  {
    id: 2009, nome: 'Barra Fixa (Pegada Supinada)', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps',
    equipamento: 'Barra fixa',
    descricao: '1. Segure a barra com pegada supinada (palmas para você), largura dos ombros.\n2. Puxe o corpo para cima focando nos bíceps e costas.\n3. Maior envolvimento do bíceps em relação à pegada pronada.\n4. Desça de forma controlada.',
  },
  {
    id: 2010, nome: 'Hiperextensão Lombar', grupoMuscular: 'Costas',
    musculosSecundarios: 'Glúteos, Posterior de coxa',
    equipamento: 'Banco romano',
    descricao: '1. Posicione-se no banco romano com os quadris na almofada e pés presos.\n2. Cruce os braços no peito ou coloque atrás da cabeça.\n3. Incline o tronco para baixo de forma controlada.\n4. Suba até o corpo ficar alinhado, espremendo glúteos e lombar.\n5. Não hiperextenda além da linha natural.',
  },
  {
    id: 2011, nome: 'Puxada no Pulley Alto', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps',
    equipamento: 'Polia alta',
    descricao: '1. Segure a barra com pegada pronada na largura dos ombros.\n2. Com os braços estendidos, puxe a barra até o queixo.\n3. Mantenha os cotovelos apontando para baixo.\n4. Retorne com controle.',
  },
  {
    id: 2012, nome: 'Serrote com Halter', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps',
    equipamento: 'Halter',
    descricao: '1. Com o tronco quase paralelo ao chão, segure um halter.\n2. Puxe o halter em direção ao quadril como se fosse puxar uma corda de serra.\n3. Retraia bem a escápula no topo.\n4. Alterne os lados.',
  },
  {
    id: 2013, nome: 'Remada Curvada com Halteres', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps, Lombar',
    equipamento: 'Halteres',
    descricao: '1. Com um halter em cada mão, incline o tronco a 45°.\n2. Puxe ambos os halteres simultaneamente em direção ao abdômen.\n3. Retraia as escápulas no topo do movimento.\n4. Maior amplitude e liberdade de movimento comparado à barra.\n5. Desça controlando até os braços estenderem.',
  },
  {
    id: 2014, nome: 'Remada na Máquina (Chest Supported)', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps, Romboides',
    equipamento: 'Máquina',
    descricao: '1. Ajuste o banco e apoie o peito na almofada.\n2. Segure as alças e puxe em direção ao corpo.\n3. O apoio no peito elimina a compensação com a lombar.\n4. Ótima opção para isolar as costas com segurança.\n5. Esprema as escápulas no final.',
  },
  {
    id: 2015, nome: 'Puxada na Polia com Pegada Neutra', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps',
    equipamento: 'Polia alta, triângulo',
    descricao: '1. Use o triângulo ou barra V na polia alta.\n2. Sente com os pés firmes e incline levemente o tronco para trás.\n3. Puxe o triângulo até a frente do peito, cotovelos apontando para baixo.\n4. Esprema as costas no final e retorne com controle.',
  },

  // ─── OMBROS ──────────────────────────────────────────────────────────────
  {
    id: 3001, nome: 'Desenvolvimento Militar com Barra', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Tríceps, Trapézio',
    equipamento: 'Barra',
    descricao: '1. Segure a barra na frente, na altura dos ombros, com pegada larga.\n2. Empurre a barra para cima até os braços ficarem estendidos.\n3. Desça controlando até a linha do queixo.\n4. Mantenha o core rígido, sem arquear a lombar.',
  },
  {
    id: 3002, nome: 'Desenvolvimento com Halteres', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Tríceps',
    equipamento: 'Halteres',
    descricao: '1. Sente com as costas apoiadas ou em pé.\n2. Segure um halter em cada mão na altura dos ombros, cotovelos a 90°.\n3. Empurre os halteres para cima convergindo levemente.\n4. Retorne à posição inicial de forma controlada.',
  },
  {
    id: 3003, nome: 'Elevação Lateral com Halteres', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Trapézio',
    equipamento: 'Halteres',
    descricao: '1. Em pé, segure um halter em cada mão ao lado do corpo.\n2. Levante os braços para os lados até a altura dos ombros (cotovelos levemente flexionados).\n3. Pense em derramar água com o polegar levemente para baixo.\n4. Desça lentamente (3 segundos).',
  },
  {
    id: 3004, nome: 'Elevação Frontal com Halteres', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Peito',
    equipamento: 'Halteres',
    descricao: '1. Em pé, segure os halteres à frente das coxas.\n2. Levante um halter de cada vez (ou ambos) até a altura dos ombros.\n3. Mantenha leve flexão nos cotovelos.\n4. Desça de forma controlada.',
  },
  {
    id: 3005, nome: 'Elevação Lateral na Polia', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Trapézio',
    equipamento: 'Polia baixa',
    descricao: '1. Ajuste a polia na posição mais baixa.\n2. Fique de lado e puxe a alça cruzando o corpo.\n3. Levante o braço lateralmente até a altura dos ombros.\n4. Retorne com tensão constante no cabo.',
  },
  {
    id: 3006, nome: 'Crucifixo Inverso com Halteres', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Romboides, Trapézio',
    equipamento: 'Halteres',
    descricao: '1. Incline o tronco a 45–90° para frente.\n2. Segure os halteres com palmas se encarando.\n3. Abra os braços para os lados até a altura dos ombros.\n4. Esprema as escápulas no topo.\n5. Desça de forma controlada.',
  },
  {
    id: 3007, nome: 'Encolhimento de Ombros com Barra', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Trapézio',
    equipamento: 'Barra',
    descricao: '1. Segure a barra na frente com os braços estendidos.\n2. Encolha os ombros em direção às orelhas o máximo possível.\n3. Mantenha por 1 segundo espremendo o trapézio.\n4. Retorne de forma controlada.\n5. Não gire os ombros.',
  },
  {
    id: 3008, nome: 'Encolhimento de Ombros com Halteres', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Trapézio',
    equipamento: 'Halteres',
    descricao: '1. Em pé, com um halter em cada mão ao lado do corpo.\n2. Encolha os ombros para cima, espremendo o trapézio.\n3. Segure 1 segundo no topo e desça de forma controlada.',
  },
  {
    id: 3009, nome: 'Face Pull na Polia', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Romboides, Manguito Rotador',
    equipamento: 'Polia alta, corda',
    descricao: '1. Ajuste a polia na altura da cabeça e use a corda.\n2. Puxe a corda em direção ao rosto, separando as mãos.\n3. Os cotovelos devem ficar acima dos ombros no final.\n4. Retorne com controle. Excelente para saúde do ombro.',
  },
  {
    id: 3010, nome: 'Desenvolvimento Arnold', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Tríceps, Trapézio',
    equipamento: 'Halteres',
    descricao: '1. Sente com os halteres na altura dos ombros, palmas voltadas para você.\n2. Ao empurrar para cima, gire os pulsos de forma que as palmas fiquem para fora no topo.\n3. Desça revertendo a rotação.\n4. Movimento completo envolvendo toda a cabeça do deltóide.',
  },
  {
    id: 3011, nome: 'Elevação Frontal com Barra', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Peito',
    equipamento: 'Barra',
    descricao: '1. Em pé, segure a barra com pegada pronada na largura dos ombros.\n2. Levante a barra à frente até a altura dos ombros com leve flexão nos cotovelos.\n3. Mantenha o tronco estável, sem balançar.\n4. Desça lentamente em 3 segundos.',
  },
  {
    id: 3012, nome: 'Desenvolvimento no Smith', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Tríceps',
    equipamento: 'Smith',
    descricao: '1. Ajuste o banco abaixo da barra do Smith.\n2. Posicione a barra na altura dos ombros, pegada pronada larga.\n3. Empurre para cima até os braços ficarem estendidos.\n4. Retorne até a linha do queixo.\n5. O Smith oferece mais estabilidade para quem está aprendendo.',
  },
  {
    id: 3013, nome: 'Elevação Lateral na Máquina', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Trapézio',
    equipamento: 'Máquina',
    descricao: '1. Sente na máquina com os cotovelos apoiados nas almofadas laterais.\n2. Eleve os braços lateralmente contra a resistência.\n3. Pare na altura dos ombros.\n4. Retorne lentamente. Tensão constante durante todo o movimento.',
  },

  // ─── BÍCEPS ──────────────────────────────────────────────────────────────
  {
    id: 4001, nome: 'Rosca Direta com Barra', grupoMuscular: 'Bíceps',
    musculosSecundarios: 'Antebraço',
    equipamento: 'Barra',
    descricao: '1. Em pé, segure a barra com pegada supinada na largura dos ombros.\n2. Mantenha os cotovelos fixos ao lado do corpo.\n3. Curl a barra até os bíceps contraírem totalmente.\n4. Desça lentamente (3 segundos) até a extensão quase completa.',
  },
  {
    id: 4002, nome: 'Rosca Alternada com Halteres', grupoMuscular: 'Bíceps',
    musculosSecundarios: 'Antebraço',
    equipamento: 'Halteres',
    descricao: '1. Em pé, com um halter em cada mão, braços ao lado do corpo.\n2. Curl um halter de cada vez, supinando o punho na subida.\n3. Esprema o bíceps no topo.\n4. Desça antes de subir o outro lado.',
  },
  {
    id: 4003, nome: 'Rosca Martelo com Halteres', grupoMuscular: 'Bíceps',
    musculosSecundarios: 'Braquiorradial, Antebraço',
    equipamento: 'Halteres',
    descricao: '1. Segure os halteres com pegada neutra (palmas se encarando).\n2. Curl os halteres sem girar os pulsos.\n3. Trabalha o braquiorradial e a parte longa do bíceps.\n4. Desça de forma controlada.',
  },
  {
    id: 4004, nome: 'Rosca Concentrada', grupoMuscular: 'Bíceps',
    musculosSecundarios: '',
    equipamento: 'Halter',
    descricao: '1. Sente em um banco com as pernas abertas.\n2. Apoie o cotovelo na parte interna da coxa.\n3. Curl o halter focando em isolar o bíceps.\n4. Esprema bem no topo antes de descer.',
  },
  {
    id: 4005, nome: 'Rosca no Cabo (Polia Baixa)', grupoMuscular: 'Bíceps',
    musculosSecundarios: 'Antebraço',
    equipamento: 'Polia baixa',
    descricao: '1. Ajuste a polia na posição baixa.\n2. Segure a barra reta ou alça e curl para cima.\n3. Tensão constante no bíceps durante todo o movimento.\n4. Ótima opção para o pico do bíceps.',
  },
  {
    id: 4006, nome: 'Rosca Scott com Barra', grupoMuscular: 'Bíceps',
    musculosSecundarios: 'Antebraço',
    equipamento: 'Barra, Banco Scott',
    descricao: '1. Apoie a parte de trás dos braços no banco inclinado.\n2. Segure a barra com pegada supinada.\n3. Curl até os bíceps estarem totalmente contraídos.\n4. Desça lentamente até quase a extensão completa (não trave totalmente).',
  },
  {
    id: 4007, nome: 'Rosca Inclinada com Halteres', grupoMuscular: 'Bíceps',
    musculosSecundarios: '',
    equipamento: 'Halteres, Banco inclinado',
    descricao: '1. Sente em um banco inclinado a 45–60°.\n2. Com os braços pendurados, curl os halteres supinando os punhos.\n3. A inclinação proporciona maior estiramento na descida.\n4. Excelente para o comprimento do bíceps.',
  },
  {
    id: 4008, nome: 'Rosca Inversa com Barra', grupoMuscular: 'Bíceps',
    musculosSecundarios: 'Braquiorradial, Antebraço',
    equipamento: 'Barra',
    descricao: '1. Segure a barra com pegada pronada (palmas para baixo).\n2. Curl a barra até a altura do queixo.\n3. Mantém mais os antebraços e o braquiorradial.\n4. Desça de forma lenta e controlada.',
  },
  {
    id: 4009, nome: 'Rosca Direta com Barra EZ', grupoMuscular: 'Bíceps',
    musculosSecundarios: 'Antebraço',
    equipamento: 'Barra EZ',
    descricao: '1. Segure a barra EZ nas empunhaduras inclinadas com pegada supinada.\n2. Cotovelos fixos ao lado do corpo.\n3. Curl a barra até os bíceps contraírem totalmente.\n4. Desça lentamente.\n5. Reduz o estresse nos pulsos comparado à barra reta.',
  },
  {
    id: 4010, nome: 'Rosca Scott com Halteres', grupoMuscular: 'Bíceps',
    musculosSecundarios: 'Antebraço',
    equipamento: 'Halteres, Banco Scott',
    descricao: '1. Apoie os braços no banco Scott inclinado.\n2. Segure um halter em cada mão com pegada supinada.\n3. Curl alternado ou simultâneo até a contração total.\n4. Desça lentamente até quase a extensão.\n5. Maior isolamento que a rosca livre.',
  },
  {
    id: 4011, nome: 'Rosca 21', grupoMuscular: 'Bíceps',
    musculosSecundarios: 'Antebraço',
    equipamento: 'Barra ou Halteres',
    descricao: 'Série de 21 repetições dividida em 3 partes:\n1. 7 reps da metade inferior (0° a 90°).\n2. 7 reps da metade superior (90° até o topo).\n3. 7 reps completas (amplitude total).\n4. Sem pausa entre as partes. Excelente para pump no bíceps.',
  },
  {
    id: 4012, nome: 'Rosca Martelo na Polia (Corda)', grupoMuscular: 'Bíceps',
    musculosSecundarios: 'Braquiorradial, Antebraço',
    equipamento: 'Polia baixa, corda',
    descricao: '1. Ajuste a polia na posição baixa e use a corda.\n2. Segure as pontas da corda com pegada neutra (palmas se encarando).\n3. Curl a corda até o pescoço mantendo os cotovelos fixos.\n4. Retorne com controle. Ótimo para o braquiorradial.',
  },

  // ─── TRÍCEPS ─────────────────────────────────────────────────────────────
  {
    id: 5001, nome: 'Tríceps Pulley (Cabo)', grupoMuscular: 'Tríceps',
    musculosSecundarios: '',
    equipamento: 'Polia alta',
    descricao: '1. Ajuste a polia na posição alta com a barra reta ou V.\n2. Fique de frente à polia, cotovelos fixos ao lado do corpo.\n3. Empurre a barra para baixo até estender completamente os braços.\n4. Retorne lentamente sem levantar os cotovelos.',
  },
  {
    id: 5002, nome: 'Tríceps Testa com Barra', grupoMuscular: 'Tríceps',
    musculosSecundarios: '',
    equipamento: 'Barra, Banco',
    descricao: '1. Deite no banco segurando a barra com pegada pronada, braços estendidos.\n2. Dobre apenas os cotovelos abaixando a barra em direção à testa.\n3. Suba estendendo os braços sem mover os cotovelos.\n4. Controle total para não bater na testa.',
  },
  {
    id: 5003, nome: 'Tríceps Francês com Halter', grupoMuscular: 'Tríceps',
    musculosSecundarios: '',
    equipamento: 'Halter',
    descricao: '1. Em pé ou sentado, segure um halter com as duas mãos acima da cabeça.\n2. Dobre os cotovelos abaixando o halter atrás da cabeça.\n3. Suba estendendo os braços, mantendo os cotovelos apontando para cima.\n4. Ótimo para a cabeça longa do tríceps.',
  },
  {
    id: 5004, nome: 'Tríceps Coice com Halter', grupoMuscular: 'Tríceps',
    musculosSecundarios: '',
    equipamento: 'Halter',
    descricao: '1. Incline o tronco a 45°, apoiado no banco ou livre.\n2. Com o braço dobrado a 90° ao lado do corpo, estenda o antebraço para trás.\n3. Esprema o tríceps no final.\n4. Retorne lentamente.',
  },
  {
    id: 5005, nome: 'Mergulho em Paralelas (Tríceps)', grupoMuscular: 'Tríceps',
    musculosSecundarios: 'Peito, Ombros',
    equipamento: 'Paralelas',
    descricao: '1. Suba nas paralelas com os braços estendidos.\n2. Mantenha o tronco ereto (foco no tríceps).\n3. Desça dobrando os cotovelos para trás até 90°.\n4. Suba empurrando, espremendo o tríceps no topo.',
  },
  {
    id: 5006, nome: 'Tríceps no Banco', grupoMuscular: 'Tríceps',
    musculosSecundarios: 'Ombros',
    equipamento: 'Banco',
    descricao: '1. Apoie as mãos na borda de um banco atrás de você.\n2. Mantenha as pernas estendidas (mais difícil) ou dobradas.\n3. Desça dobrando os cotovelos até 90°.\n4. Empurre de volta à posição inicial.',
  },
  {
    id: 5007, nome: 'Tríceps Corda no Cabo', grupoMuscular: 'Tríceps',
    musculosSecundarios: '',
    equipamento: 'Polia alta, corda',
    descricao: '1. Use a corda no cabo alto.\n2. Segure as pontas da corda e empurre para baixo.\n3. Ao final, abra as mãos para os lados para maximizar a contração.\n4. Retorne lentamente.',
  },
  {
    id: 5008, nome: 'Supino Fechado', grupoMuscular: 'Tríceps',
    musculosSecundarios: 'Peito, Ombros',
    equipamento: 'Barra, Banco',
    descricao: '1. Deite no banco com a barra acima do peito.\n2. Use pegada pronada com as mãos na largura dos ombros ou mais próximas.\n3. Desça a barra ao peito baixo.\n4. Empurre focando em usar o tríceps.',
  },
  {
    id: 5009, nome: 'Tríceps Testa com Halteres', grupoMuscular: 'Tríceps',
    musculosSecundarios: '',
    equipamento: 'Halteres, Banco',
    descricao: '1. Deite no banco segurando um halter em cada mão, braços estendidos acima do peito.\n2. Dobre apenas os cotovelos abaixando os halteres em direção às têmporas/testa.\n3. Os cotovelos ficam fixos apontando para o teto.\n4. Estenda os braços voltando à posição inicial.\n5. Maior amplitude de movimento comparado à barra — explora melhor o estiramento.',
  },
  {
    id: 5010, nome: 'Tríceps Testa na Polia', grupoMuscular: 'Tríceps',
    musculosSecundarios: '',
    equipamento: 'Polia baixa, barra reta',
    descricao: '1. Ajuste a polia na posição mais baixa com a barra reta ou EZ.\n2. Deite no banco posicionado atrás da polia.\n3. Segure a barra com os braços estendidos apontando para a polia.\n4. Dobre os cotovelos abaixando a barra em direção à testa.\n5. Tensão constante no tríceps graças ao cabo. Ótima variação para a porção longa.',
  },
  {
    id: 5011, nome: 'Tríceps Francês com Barra EZ', grupoMuscular: 'Tríceps',
    musculosSecundarios: '',
    equipamento: 'Barra EZ',
    descricao: '1. Em pé ou sentado, segure a barra EZ com os braços estendidos acima da cabeça.\n2. Dobre os cotovelos abaixando a barra atrás da cabeça.\n3. Cotovelos apontados para o teto durante todo o movimento.\n4. Suba estendendo os braços.\n5. A barra EZ reduz o estresse nos pulsos.',
  },
  {
    id: 5012, nome: 'Tríceps Francês na Polia', grupoMuscular: 'Tríceps',
    musculosSecundarios: '',
    equipamento: 'Polia alta, corda',
    descricao: '1. Ajuste a polia alta e use a corda.\n2. De costas para a máquina, segure a corda atrás da cabeça com os cotovelos dobrados.\n3. Estenda os braços para frente empurrando a corda.\n4. Retorne lentamente dobrando os cotovelos atrás da cabeça.\n5. Tensão constante na cabeça longa do tríceps.',
  },
  {
    id: 5013, nome: 'Tríceps Coice na Polia', grupoMuscular: 'Tríceps',
    musculosSecundarios: '',
    equipamento: 'Polia baixa',
    descricao: '1. Ajuste a polia baixa e prenda a alça.\n2. Incline o tronco a 45° com o braço dobrado a 90°.\n3. Estenda o antebraço para trás contra a resistência do cabo.\n4. Esprema o tríceps na extensão completa.\n5. Tensão constante diferente do halter — sem perda de resistência no topo.',
  },
  {
    id: 5014, nome: 'Tríceps Pulley com V Bar', grupoMuscular: 'Tríceps',
    musculosSecundarios: '',
    equipamento: 'Polia alta, V bar',
    descricao: '1. Use o V bar (triângulo) na polia alta.\n2. Fique de frente, cotovelos fixos ao lado do corpo.\n3. Empurre o V bar para baixo até estender completamente os braços.\n4. Retorne lentamente sem levantar os cotovelos.\n5. A pegada neutra do V bar reduz estresse nos pulsos.',
  },

  // ─── PERNAS ──────────────────────────────────────────────────────────────
  {
    id: 6001, nome: 'Agachamento Livre com Barra', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos, Lombar, Core',
    equipamento: 'Barra, Rack',
    descricao: '1. Barra sobre a parte superior das costas, pés na largura dos ombros.\n2. Empurre os joelhos para fora na mesma direção dos dedos.\n3. Desça até a coxa ficar paralela (ou abaixo) ao chão.\n4. Mantenha o peito ereto e a lombar neutra.\n5. Suba empurrando o chão com os pés.',
  },
  {
    id: 6002, nome: 'Leg Press 45°', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos',
    equipamento: 'Máquina Leg Press',
    descricao: '1. Sente na máquina com os pés na plataforma na largura dos ombros.\n2. Solte as travas e dobre os joelhos até ~90°.\n3. Empurre a plataforma de volta sem travar os joelhos no topo.\n4. Pés mais altos = mais glúteos; mais baixos = mais quadríceps.',
  },
  {
    id: 6003, nome: 'Extensão de Joelhos (Cadeira Extensora)', grupoMuscular: 'Pernas',
    musculosSecundarios: '',
    equipamento: 'Máquina',
    descricao: '1. Sente na máquina com os joelhos dobrados a 90° ou menos.\n2. Estenda as pernas até quase a extensão total.\n3. Segure 1 segundo espremendo o quadríceps.\n4. Retorne lentamente em 3–4 segundos.',
  },
  {
    id: 6004, nome: 'Flexão de Joelhos (Mesa Flexora)', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos',
    equipamento: 'Máquina',
    descricao: '1. Deite de bruços com os tornozelos sob o apoio da máquina.\n2. Dobre os joelhos puxando os calcanhares em direção aos glúteos.\n3. Esprema o posterior de coxa no topo.\n4. Desça lentamente.',
  },
  {
    id: 6005, nome: 'Agachamento Hack', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos',
    equipamento: 'Máquina Hack Squat',
    descricao: '1. Posicione-se na máquina com os ombros sob as almofadas.\n2. Pés na largura dos ombros na plataforma.\n3. Desça até a coxa ficar paralela ou abaixo.\n4. Suba empurrando com os calcanhares.',
  },
  {
    id: 6006, nome: 'Avanço (Lunges) com Halteres', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos, Core',
    equipamento: 'Halteres',
    descricao: '1. Em pé com um halter em cada mão.\n2. Dê um passo largo para frente.\n3. Desça até o joelho traseiro quase tocar o chão.\n4. O joelho da frente não deve ultrapassar muito os dedos dos pés.\n5. Suba e alterne as pernas.',
  },
  {
    id: 6007, nome: 'Stiff com Barra', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos, Lombar',
    equipamento: 'Barra',
    descricao: '1. Em pé segurando a barra à frente, pernas levemente dobradas.\n2. Incline o tronco para frente empurrando o quadril para trás.\n3. Desça a barra próxima às pernas até sentir o posterior de coxa esticar.\n4. Suba contraindo o posterior e os glúteos.',
  },
  {
    id: 6008, nome: 'Agachamento Goblet com Halter', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Core, Glúteos',
    equipamento: 'Halter ou Kettlebell',
    descricao: '1. Segure um halter verticalmente na frente do peito.\n2. Pés levemente mais abertos que os ombros, dedos apontando para fora.\n3. Desça em agachamento profundo mantendo o tronco ereto.\n4. Suba empurrando o chão.',
  },
  {
    id: 6009, nome: 'Passada com Barra', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos, Core',
    equipamento: 'Barra',
    descricao: '1. Barra sobre os ombros como no agachamento.\n2. Dê um passo largo alternando as pernas.\n3. Desça até o joelho traseiro quase tocar o chão.\n4. Mantenha o tronco ereto durante todo o movimento.',
  },
  {
    id: 6010, nome: 'Agachamento Búlgaro', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos, Core',
    equipamento: 'Halteres ou Barra, Banco',
    descricao: '1. Apoie o pé de trás em um banco atrás de você.\n2. O pé da frente fica à frente do corpo.\n3. Desça dobrando o joelho da frente até 90°.\n4. Suba empurrando com o calcanhar da frente.',
  },
  {
    id: 6011, nome: 'Cadeira Adutora', grupoMuscular: 'Pernas',
    musculosSecundarios: '',
    equipamento: 'Máquina',
    descricao: '1. Sente com as pernas abertas nas almofadas externas.\n2. Feche as pernas contra a resistência da máquina.\n3. Esprema os adutores no final.\n4. Retorne lentamente.',
  },
  {
    id: 6012, nome: 'Cadeira Abdutora', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos',
    equipamento: 'Máquina',
    descricao: '1. Sente com as pernas juntas nas almofadas internas.\n2. Abra as pernas contra a resistência da máquina.\n3. Esprema os abdutores e glúteos no final.\n4. Retorne lentamente.',
  },
  {
    id: 6013, nome: 'Agachamento Sumô', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Adutores, Glúteos',
    equipamento: 'Barra ou Halter',
    descricao: '1. Pés bem mais abertos que os ombros, dedos apontando para fora.\n2. Desça em agachamento mantendo o tronco ereto.\n3. Joelhos na mesma direção dos dedos.\n4. Sobe espremendo adutores e glúteos.',
  },
  {
    id: 6014, nome: 'Leg Press Unilateral', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos',
    equipamento: 'Máquina Leg Press',
    descricao: '1. Posicione apenas um pé no centro da plataforma.\n2. Execute o movimento com uma perna de cada vez.\n3. Corrige desequilíbrios entre as pernas.\n4. Controle total na descida.',
  },
  {
    id: 6015, nome: 'Agachamento Frontal com Barra', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Core, Ombros',
    equipamento: 'Barra',
    descricao: '1. Barra apoiada na frente dos ombros, cotovelos altos.\n2. Pés na largura dos ombros.\n3. Desça mantendo o tronco bem ereto.\n4. Maior ativação do quadríceps em relação ao agachamento convencional.',
  },
  {
    id: 6016, nome: 'Stiff Unilateral com Halter', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos, Lombar',
    equipamento: 'Halter',
    descricao: '1. Em pé em uma perna, segure o halter à frente do corpo.\n2. Incline o tronco para frente enquanto a perna livre se eleva atrás.\n3. Desça até sentir o posterior da perna de apoio esticar.\n4. Suba contraindo o glúteo e posterior.',
  },
  {
    id: 6017, nome: 'Stiff com Halteres', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos, Lombar',
    equipamento: 'Halteres',
    descricao: '1. Em pé com um halter em cada mão à frente das coxas.\n2. Pernas levemente dobradas, lombar neutra.\n3. Incline o tronco para frente empurrando o quadril para trás.\n4. Desça os halteres próximos às pernas sentindo o posterior esticar.\n5. Suba contraindo posterior e glúteos.',
  },
  {
    id: 6018, nome: 'Flexão de Joelhos em Pé (Máquina)', grupoMuscular: 'Pernas',
    musculosSecundarios: '',
    equipamento: 'Máquina',
    descricao: '1. Fique em pé na máquina com o tornozelo sob o apoio.\n2. Dobre o joelho puxando o calcanhar em direção ao glúteo.\n3. Esprema o posterior no topo.\n4. Desça lentamente.\n5. Ativação diferente da mesa flexora — trabalha o músculo em posição mais alongada.',
  },
  {
    id: 6019, nome: 'Agachamento no Smith', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos, Core',
    equipamento: 'Smith',
    descricao: '1. Posicione a barra do Smith nos ombros.\n2. Pés um pouco à frente do alinhamento da barra.\n3. Desça até a coxa paralela ou abaixo.\n4. O Smith guia o movimento — boa opção para iniciantes ou lesionados.\n5. Suba empurrando o chão com os calcanhares.',
  },
  {
    id: 6020, nome: 'Cadeira Extensora Unilateral', grupoMuscular: 'Pernas',
    musculosSecundarios: '',
    equipamento: 'Máquina',
    descricao: '1. Sente na cadeira extensora e use apenas uma perna.\n2. Estenda até quase a extensão total.\n3. Segure 1 segundo espremendo o quadríceps.\n4. Retorne lentamente em 3–4 segundos.\n5. Corrige desequilíbrios entre as pernas.',
  },

  // ─── PANTURRILHA ─────────────────────────────────────────────────────────
  {
    id: 7001, nome: 'Panturrilha em Pé (Gêmeos)', grupoMuscular: 'Panturrilha',
    musculosSecundarios: '',
    equipamento: 'Máquina ou Halter',
    descricao: '1. Fique em pé com as pontas dos pés em uma plataforma elevada.\n2. Desça os calcanhares abaixo da plataforma para estirar o músculo.\n3. Suba na ponta dos pés o máximo possível.\n4. Segure 1 segundo no topo.\n5. Use pesos adicionais para progressão.',
  },
  {
    id: 7002, nome: 'Panturrilha Sentado (Sóleo)', grupoMuscular: 'Panturrilha',
    musculosSecundarios: '',
    equipamento: 'Máquina',
    descricao: '1. Sente na máquina com os joelhos a 90°.\n2. Pesos apoiados acima dos joelhos.\n3. Eleve os calcanhares na ponta dos pés.\n4. Segure no topo e desça controlando.\n5. Com os joelhos dobrados, o foco vai para o sóleo.',
  },
  {
    id: 7003, nome: 'Panturrilha no Leg Press', grupoMuscular: 'Panturrilha',
    musculosSecundarios: '',
    equipamento: 'Máquina Leg Press',
    descricao: '1. Posicione apenas as pontas dos pés na parte inferior da plataforma.\n2. Com as pernas quase estendidas, empurre a plataforma com as pontas dos pés.\n3. Esprema a panturrilha no topo.\n4. Retorne baixando os calcanhares além do nível neutro.',
  },
  {
    id: 7004, nome: 'Panturrilha Unilateral com Halter', grupoMuscular: 'Panturrilha',
    musculosSecundarios: '',
    equipamento: 'Halter, Degrau',
    descricao: '1. Fique em um pé só na borda de um degrau, segurando um halter.\n2. Desça o calcanhar abaixo do degrau.\n3. Suba na ponta do pé o máximo possível.\n4. Alternando os lados.',
  },
  {
    id: 7005, nome: 'Panturrilha no Smith', grupoMuscular: 'Panturrilha',
    musculosSecundarios: '',
    equipamento: 'Smith, Degrau',
    descricao: '1. Posicione as pontas dos pés em uma plataforma elevada sob o Smith.\n2. Barra apoiada nos ombros como no agachamento.\n3. Desça os calcanhares abaixo do nível dos pés.\n4. Suba na ponta dos pés o máximo possível, espremendo as panturrilhas.\n5. Permite carga maior que o halter unilateral.',
  },

  // ─── GLÚTEOS ─────────────────────────────────────────────────────────────
  {
    id: 8001, nome: 'Hip Thrust com Barra', grupoMuscular: 'Glúteos',
    musculosSecundarios: 'Posterior de coxa, Core',
    equipamento: 'Barra, Banco',
    descricao: '1. Apoie as escápulas em um banco com os pés no chão.\n2. Barra sobre o quadril (use almofada).\n3. Empurre o quadril para cima espremendo os glúteos.\n4. No topo, o tronco deve estar paralelo ao chão.\n5. Desça controlando sem tocar os glúteos no chão.',
  },
  {
    id: 8002, nome: 'Elevação Pélvica no Banco', grupoMuscular: 'Glúteos',
    musculosSecundarios: 'Posterior de coxa',
    equipamento: 'Banco',
    descricao: '1. Deite com as costas no chão, pés apoiados no banco.\n2. Eleve o quadril espremendo os glúteos no topo.\n3. Versão mais simples do Hip Thrust.\n4. Adicione peso sobre o quadril para progressão.',
  },
  {
    id: 8003, nome: 'Glúteo no Cabo (Kickback)', grupoMuscular: 'Glúteos',
    musculosSecundarios: 'Posterior de coxa',
    equipamento: 'Polia baixa',
    descricao: '1. Prenda a alça no tornozelo e ajuste a polia na posição baixa.\n2. Apoie-se na máquina ou em uma superfície firme.\n3. Empurre a perna para trás estendendo o quadril.\n4. Esprema o glúteo no final e retorne controlando.',
  },
  {
    id: 8004, nome: 'Agachamento Sumô com Halter', grupoMuscular: 'Glúteos',
    musculosSecundarios: 'Adutores, Pernas',
    equipamento: 'Halter ou Kettlebell',
    descricao: '1. Pés largos com dedos apontando para fora.\n2. Segure um halter verticalmente entre as pernas.\n3. Desça com o tronco ereto sentindo adutores e glúteos.\n4. Suba espremendo glúteos.',
  },
  {
    id: 8005, nome: 'Avanço com Passada Longa', grupoMuscular: 'Glúteos',
    musculosSecundarios: 'Pernas',
    equipamento: 'Peso corporal ou Halteres',
    descricao: '1. Dê um passo bem longo para frente.\n2. Desça profundamente até o joelho traseiro tocar o chão.\n3. Foco em empurrar com o calcanhar da frente para ativar mais o glúteo.\n4. Retorne e alterne os lados.',
  },
  {
    id: 8006, nome: 'Glúteo na Máquina (Extensão de Quadril)', grupoMuscular: 'Glúteos',
    musculosSecundarios: 'Posterior de coxa',
    equipamento: 'Máquina',
    descricao: '1. Posicione-se na máquina com o quadril na almofada.\n2. Empurre para trás estendendo o quadril o máximo possível.\n3. Esprema no final e retorne com controle.',
  },
  {
    id: 8007, nome: 'Hip Thrust com Halter', grupoMuscular: 'Glúteos',
    musculosSecundarios: 'Posterior de coxa',
    equipamento: 'Halter, Banco',
    descricao: '1. Apoie as escápulas em um banco com os pés no chão.\n2. Segure um halter sobre o quadril com as duas mãos.\n3. Empurre o quadril para cima espremendo os glúteos.\n4. No topo, o tronco deve estar paralelo ao chão.\n5. Versão mais acessível que a barra para iniciantes.',
  },
  {
    id: 8008, nome: 'Glúteo 4 Apoios na Polia', grupoMuscular: 'Glúteos',
    musculosSecundarios: 'Core',
    equipamento: 'Polia baixa',
    descricao: '1. Prenda a alça no tornozelo e ajuste a polia na posição baixa.\n2. Apoie-se em 4 apoios (mãos e joelhos) de costas para a máquina.\n3. Empurre a perna para cima e para trás estendendo o quadril.\n4. Esprema o glúteo no topo por 1 segundo.\n5. Retorne controlando sem tocar o joelho no chão.',
  },
  {
    id: 8009, nome: 'Abdução de Quadril no Cabo', grupoMuscular: 'Glúteos',
    musculosSecundarios: 'Abdutores',
    equipamento: 'Polia baixa',
    descricao: '1. Prenda a alça no tornozelo e fique de lado para a máquina.\n2. Mantendo a perna reta, abra lateralmente contra a resistência do cabo.\n3. Esprema o glúteo médio no final.\n4. Retorne com controle sem cruzar demais a perna.\n5. Trabalha o glúteo médio e mínimo.',
  },

  // ─── ABDÔMEN ─────────────────────────────────────────────────────────────
  {
    id: 9001, nome: 'Abdominal Crunch', grupoMuscular: 'Abdômen',
    musculosSecundarios: '',
    equipamento: 'Peso corporal',
    descricao: '1. Deite de costas com os joelhos dobrados.\n2. Mãos atrás da cabeça (sem puxar o pescoço).\n3. Contraia o abdômen levantando apenas os ombros do chão.\n4. Expire na subida.\n5. Não force o pescoço.',
  },
  {
    id: 9002, nome: 'Abdominal no Cabo', grupoMuscular: 'Abdômen',
    musculosSecundarios: '',
    equipamento: 'Polia alta, corda',
    descricao: '1. Ajoelhe-se de frente à polia alta com a corda.\n2. Segure a corda na altura da cabeça.\n3. Contraia o abdômen flexionando o tronco para baixo.\n4. Mantenha o quadril estático.\n5. Retorne de forma controlada.',
  },
  {
    id: 9003, nome: 'Elevação de Pernas', grupoMuscular: 'Abdômen',
    musculosSecundarios: 'Flexores do quadril',
    equipamento: 'Barra fixa ou banco',
    descricao: '1. Pendurado na barra ou apoiado nos cotovelos.\n2. Mantenha as pernas retas ou levemente dobradas.\n3. Eleve as pernas até 90° (ou mais).\n4. Desça de forma controlada sem balançar.',
  },
  {
    id: 9004, nome: 'Prancha (Plank)', grupoMuscular: 'Abdômen',
    musculosSecundarios: 'Core, Ombros',
    equipamento: 'Peso corporal',
    descricao: '1. Posição de apoio nos antebraços e pontas dos pés.\n2. Corpo alinhado da cabeça aos calcanhares.\n3. Core contraído, glúteos espremidos.\n4. Não deixe o quadril cair ou subir.\n5. Segure pelo tempo desejado.',
  },
  {
    id: 9005, nome: 'Oblíquo Russo (Russian Twist)', grupoMuscular: 'Abdômen',
    musculosSecundarios: 'Oblíquos',
    equipamento: 'Peso ou halter',
    descricao: '1. Sente no chão com os joelhos dobrados, tronco reclinado a 45°.\n2. Segure um peso com as duas mãos.\n3. Gire o tronco de lado a lado tocando o peso no chão.\n4. Para aumentar: levante os pés do chão.',
  },
  {
    id: 9006, nome: 'Mountain Climber', grupoMuscular: 'Abdômen',
    musculosSecundarios: 'Core, Cardio',
    equipamento: 'Peso corporal',
    descricao: '1. Posição de flexão de braço.\n2. Leve um joelho em direção ao peito rapidamente.\n3. Alterne as pernas em ritmo acelerado.\n4. Mantenha o core contraído e o quadril estável.',
  },
  {
    id: 9007, nome: 'Abdominal Infra (Elevação de Quadril)', grupoMuscular: 'Abdômen',
    musculosSecundarios: '',
    equipamento: 'Peso corporal',
    descricao: '1. Deite de costas com as pernas elevadas a 90°.\n2. Contraia o abdômen inferior elevando o quadril do chão.\n3. Retorne lentamente.\n4. O movimento é pequeno, foque na contração.',
  },
  {
    id: 9008, nome: 'Roda Abdominal (Ab Wheel)', grupoMuscular: 'Abdômen',
    musculosSecundarios: 'Core, Costas',
    equipamento: 'Roda abdominal',
    descricao: '1. Ajoelhe-se segurando a roda abdominal.\n2. Role para frente mantendo o core contraído.\n3. Vá até onde conseguir sem perder a forma.\n4. Puxe de volta usando o abdômen, não as costas.',
  },
  {
    id: 9009, nome: 'Abdominal Bicicleta', grupoMuscular: 'Abdômen',
    musculosSecundarios: 'Oblíquos',
    equipamento: 'Peso corporal',
    descricao: '1. Deite com as mãos atrás da cabeça e os pés elevados.\n2. Leve o cotovelo direito ao joelho esquerdo enquanto estende a perna direita.\n3. Alterne os lados em movimento contínuo de pedalada.\n4. Mantenha a lombar encostada no chão.\n5. Ótimo para oblíquos e reto abdominal.',
  },
  {
    id: 9010, nome: 'Crunch Reverso', grupoMuscular: 'Abdômen',
    musculosSecundarios: 'Flexores do quadril',
    equipamento: 'Peso corporal',
    descricao: '1. Deite de costas com as pernas elevadas a 90°.\n2. Contraindo o abdômen inferior, traga os joelhos em direção ao peito.\n3. Eleve levemente o quadril do chão.\n4. Retorne lentamente sem deixar os pés tocarem o chão.\n5. Foco no abdômen inferior.',
  },
  {
    id: 9011, nome: 'Prancha Lateral', grupoMuscular: 'Abdômen',
    musculosSecundarios: 'Oblíquos, Quadril',
    equipamento: 'Peso corporal',
    descricao: '1. Deite de lado apoiado no antebraço e no pé.\n2. Eleve o quadril formando uma linha reta do ombro ao pé.\n3. Core contraído, quadril sem cair.\n4. Segure pelo tempo desejado.\n5. Excelente para oblíquos e estabilidade lateral.',
  },

  // ─── ANTEBRAÇO ───────────────────────────────────────────────────────────
  {
    id: 10001, nome: 'Rosca de Pulso com Barra', grupoMuscular: 'Antebraço',
    musculosSecundarios: '',
    equipamento: 'Barra',
    descricao: '1. Sente em um banco com os antebraços apoiados nas coxas.\n2. Segure a barra com pegada supinada.\n3. Flexione os pulsos para cima o máximo possível.\n4. Desça de forma controlada.',
  },
  {
    id: 10002, nome: 'Rosca de Pulso Inversa', grupoMuscular: 'Antebraço',
    musculosSecundarios: '',
    equipamento: 'Barra',
    descricao: '1. Mesma posição da rosca de pulso normal.\n2. Pegada pronada (palmas para baixo).\n3. Eleve os pulsos para cima contra a resistência.\n4. Trabalha o lado extensor do antebraço.',
  },
  {
    id: 10003, nome: 'Farmer Walk (Caminhada com Peso)', grupoMuscular: 'Antebraço',
    musculosSecundarios: 'Trapézio, Core',
    equipamento: 'Halteres pesados',
    descricao: '1. Segure halteres pesados em cada mão ao lado do corpo.\n2. Caminhe por uma distância determinada mantendo postura ereta.\n3. Core contraído, ombros para trás.\n4. Ótimo para força de pegada e funcional.',
  },

  // ─── CARDIO / FUNCIONAIS ─────────────────────────────────────────────────
  {
    id: 11001, nome: 'Esteira', grupoMuscular: 'Cardio',
    musculosSecundarios: 'Pernas',
    equipamento: 'Esteira',
    descricao: 'Configure velocidade e inclinação conforme seu objetivo:\n• Aquecimento: 5 km/h por 5 min\n• Moderado: 7–9 km/h\n• Intenso: 10–12 km/h ou inclinação acima de 5°\n• HIIT: alterne 1 min rápido / 1 min lento',
  },
  {
    id: 11002, nome: 'Bicicleta Ergométrica', grupoMuscular: 'Cardio',
    musculosSecundarios: 'Pernas',
    equipamento: 'Bicicleta ergométrica',
    descricao: 'Ajuste o banco para que os joelhos fiquem levemente dobrados no ponto mais baixo.\n• Resistência baixa = aeróbico leve\n• Resistência alta = força e potência\n• Cadência recomendada: 70–90 RPM',
  },
  {
    id: 11003, nome: 'Elíptico', grupoMuscular: 'Cardio',
    musculosSecundarios: 'Pernas, Braços',
    equipamento: 'Elíptico',
    descricao: 'Exercício de baixo impacto para articulações.\n• Excelente para quem tem dores nos joelhos.\n• Use os braços ativamente.\n• Varie resistência e velocidade para intensidade.',
  },
  {
    id: 11004, nome: 'Remo Ergométrico', grupoMuscular: 'Cardio',
    musculosSecundarios: 'Costas, Pernas, Core',
    equipamento: 'Remo ergométrico',
    descricao: '1. Pés presos no suporte, posição inicial com joelhos dobrados.\n2. Empurre com as pernas, incline o tronco para trás e puxe o remo ao abdômen.\n3. Retorne na ordem inversa: braços, tronco, pernas.\n4. Frequência: 18–24 remadas por minuto.',
  },
  {
    id: 11005, nome: 'Corda de Pular', grupoMuscular: 'Cardio',
    musculosSecundarios: 'Panturrilha, Ombros',
    equipamento: 'Corda',
    descricao: '• Fique nos dedos dos pés com os joelhos levemente dobrados.\n• Gire a corda pelos pulsos, não pelos braços.\n• Comece com 30 seg e aumente progressivamente.\n• Ótimo para coordenação e condicionamento.',
  },
  {
    id: 11006, nome: 'Burpee', grupoMuscular: 'Cardio',
    musculosSecundarios: 'Corpo inteiro',
    equipamento: 'Peso corporal',
    descricao: '1. Em pé, desça em agachamento e apoie as mãos no chão.\n2. Salte os pés para trás, chegando em posição de flexão.\n3. Faça uma flexão (opcional).\n4. Salte os pés de volta e suba em salto com os braços acima da cabeça.',
  },
  {
    id: 11007, nome: 'Kettlebell Swing', grupoMuscular: 'Cardio',
    musculosSecundarios: 'Glúteos, Posterior de coxa, Core',
    equipamento: 'Kettlebell',
    descricao: '1. Pés na largura dos ombros, kettlebell entre os pés.\n2. Pegue com as duas mãos, incline o tronco e impulsione com o quadril.\n3. Deixe o kettlebell balançar até a altura dos ombros.\n4. Retorne com controle curvando o quadril (não a lombar).',
  },

  // ─── PEITO (adicionais) ────────────────────────────────────────────────
  {
    id: 1017, nome: 'Supino no Smith', grupoMuscular: 'Peito',
    musculosSecundarios: 'Tríceps, Ombros',
    equipamento: 'Smith Machine, Banco',
    descricao: '1. Ajuste o banco sob a barra guiada do Smith.\n2. Segure a barra com pegada larga e destrave.\n3. Desça até o peito de forma controlada.\n4. Empurre para cima até extensão quase completa.\n5. A barra guiada ajuda na estabilidade e segurança.',
  },
  {
    id: 1018, nome: 'Chest Press na Máquina', grupoMuscular: 'Peito',
    musculosSecundarios: 'Tríceps, Ombros',
    equipamento: 'Máquina',
    descricao: '1. Ajuste o banco para que as pegadas fiquem na altura do peito.\n2. Segure as pegadas e empurre para frente.\n3. Retorne de forma controlada sem deixar os pesos baterem.\n4. Ótimo para iniciantes e para isolar o peitoral.',
  },
  {
    id: 1019, nome: 'Supino Inclinado no Smith', grupoMuscular: 'Peito',
    musculosSecundarios: 'Tríceps, Ombros',
    equipamento: 'Smith Machine, Banco inclinado',
    descricao: '1. Posicione o banco inclinado a 30–45° sob o Smith.\n2. Pegada um pouco mais larga que os ombros.\n3. Desça a barra guiada até a parte superior do peito.\n4. Empurre para cima controlando o movimento.',
  },
  {
    id: 1020, nome: 'Crucifixo Declinado com Halteres', grupoMuscular: 'Peito',
    musculosSecundarios: 'Ombros',
    equipamento: 'Halteres, Banco declinado',
    descricao: '1. Prenda os pés e deite no banco declinado com halteres.\n2. Abra os braços em arco controlado para os lados.\n3. Mantenha cotovelos levemente flexionados.\n4. Fecho o arco espremendo a porção inferior do peito.',
  },
  {
    id: 1021, nome: 'Supino Reto Pegada Fechada', grupoMuscular: 'Peito',
    musculosSecundarios: 'Tríceps',
    equipamento: 'Barra, Banco',
    descricao: '1. Deite no banco e segure a barra com pegada na largura dos ombros ou mais estreita.\n2. Desça a barra até o peito mantendo os cotovelos próximos ao corpo.\n3. Empurre para cima focando na contração do peitoral interno e tríceps.',
  },
  {
    id: 1022, nome: 'Crucifixo no Cabo Inclinado', grupoMuscular: 'Peito',
    musculosSecundarios: 'Ombros',
    equipamento: 'Cabos, Banco inclinado',
    descricao: '1. Posicione banco inclinado entre duas polias baixas.\n2. Segure as pegadas e abra em arco como um crucifixo.\n3. Feche os braços convergindo no topo.\n4. Tensão constante durante todo o movimento.',
  },
  {
    id: 1023, nome: 'Svend Press', grupoMuscular: 'Peito',
    musculosSecundarios: 'Ombros',
    equipamento: 'Anilha',
    descricao: '1. Em pé, segure uma anilha entre as palmas das mãos na altura do peito.\n2. Empurre a anilha para frente estendendo os braços.\n3. Retorne ao peito mantendo a pressão entre as palmas.\n4. Excelente para contração isométrica do peitoral.',
  },
  {
    id: 1024, nome: 'Floor Press com Halteres', grupoMuscular: 'Peito',
    musculosSecundarios: 'Tríceps',
    equipamento: 'Halteres',
    descricao: '1. Deite no chão com os joelhos dobrados e halteres na mão.\n2. Desça os halteres até os cotovelos tocarem o chão.\n3. Empurre para cima até extensão quase completa.\n4. Elimina o impulso das pernas, isolando peito e tríceps.',
  },
  {
    id: 1025, nome: 'Chest Press Declinado na Máquina', grupoMuscular: 'Peito',
    musculosSecundarios: 'Tríceps',
    equipamento: 'Máquina',
    descricao: '1. Ajuste o assento da máquina de chest press declinada.\n2. Segure as pegadas e empurre para frente e levemente para baixo.\n3. Retorne de forma controlada.\n4. Foca na porção inferior do peitoral.',
  },
  {
    id: 1026, nome: 'Cable Chest Press', grupoMuscular: 'Peito',
    musculosSecundarios: 'Tríceps, Ombros',
    equipamento: 'Cabos',
    descricao: '1. Posicione as polias na altura do peito.\n2. Segure as pegadas e dê um passo à frente.\n3. Empurre ambas as mãos para frente até os braços estenderem.\n4. Retorne lentamente sentindo a tensão constante nos cabos.',
  },

  // ─── COSTAS (adicionais) ───────────────────────────────────────────────
  {
    id: 2016, nome: 'Pendlay Row', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps, Posterior de ombro',
    equipamento: 'Barra',
    descricao: '1. Tronco paralelo ao chão, barra no solo.\n2. Puxe explosivamente até o abdômen.\n3. Retorne a barra ao chão a cada repetição.\n4. Mantém postura rígida, trabalha costas com força explosiva.',
  },
  {
    id: 2017, nome: 'Remada Inversa (Barra Fixa Australiana)', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps, Posterior de ombro',
    equipamento: 'Barra fixa baixa',
    descricao: '1. Posicione-se sob uma barra baixa com o corpo estendido.\n2. Segure a barra com pegada pronada na largura dos ombros.\n3. Puxe o peito em direção à barra mantendo o corpo reto.\n4. Desça de forma controlada.',
  },
  {
    id: 2018, nome: 'Pulldown com Braço Reto', grupoMuscular: 'Costas',
    musculosSecundarios: 'Tríceps longo',
    equipamento: 'Polia alta',
    descricao: '1. Fique de pé em frente à polia alta com barra reta.\n2. Braços estendidos, empurre a barra para baixo até as coxas.\n3. Retorne lentamente ao nível dos ombros.\n4. Isola o latíssimo sem ação do bíceps.',
  },
  {
    id: 2019, nome: 'Remada no Cabo Pegada Neutra (V-Bar)', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps, Trapézio',
    equipamento: 'Polia baixa, V-Bar',
    descricao: '1. Sente na remada com pegada neutra (V-bar).\n2. Puxe até o abdômen apertando as escápulas.\n3. Retorne de forma controlada mantendo o tronco estável.\n4. Foco na contração do meio das costas.',
  },
  {
    id: 2020, nome: 'Puxada Unilateral na Polia', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps',
    equipamento: 'Polia alta',
    descricao: '1. Sente na máquina de pulldown com uma pegada de mão.\n2. Puxe com um braço de cada vez até a altura do peito.\n3. Retorne de forma controlada.\n4. Permite corrigir assimetrias entre os lados.',
  },
  {
    id: 2021, nome: 'Remada Curvada Pegada Supinada', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps, Lombar',
    equipamento: 'Barra',
    descricao: '1. Incline o tronco a 45° segurando a barra com palmas para cima.\n2. Puxe a barra até o abdômen inferior.\n3. Retorne de forma controlada.\n4. Maior ênfase no bíceps e latíssimo inferior.',
  },
  {
    id: 2022, nome: 'Remada High Row na Máquina', grupoMuscular: 'Costas',
    musculosSecundarios: 'Posterior de ombro, Bíceps',
    equipamento: 'Máquina',
    descricao: '1. Sente na máquina de high row com o peito apoiado.\n2. Puxe as pegadas para trás na altura dos ombros.\n3. Aperte as escápulas no final do movimento.\n4. Retorne de forma controlada.',
  },
  {
    id: 2023, nome: 'Remada no Smith', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps, Lombar',
    equipamento: 'Smith Machine',
    descricao: '1. Incline o tronco e segure a barra guiada com pegada pronada.\n2. Puxe a barra até o abdômen.\n3. Retorne de forma controlada.\n4. A barra guiada estabiliza o movimento.',
  },
  {
    id: 2024, nome: 'Muscle Up', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps, Tríceps, Peito, Ombros',
    equipamento: 'Barra fixa',
    descricao: '1. Pendure na barra com pegada pronada.\n2. Puxe explosivamente levando o corpo acima da barra.\n3. Transite para posição de apoio (dip) acima da barra.\n4. Empurre para cima e desça controladamente.\n5. Movimento avançado que combina puxada e mergulho.',
  },
  {
    id: 2025, nome: 'Pullover na Máquina', grupoMuscular: 'Costas',
    musculosSecundarios: 'Peito, Tríceps longo',
    equipamento: 'Máquina',
    descricao: '1. Sente na máquina de pullover com os braços no suporte acolchoado.\n2. Empurre o suporte para baixo em arco até as coxas.\n3. Retorne de forma controlada acima da cabeça.\n4. Excelente para isolar o latíssimo.',
  },

  // ─── OMBROS (adicionais) ───────────────────────────────────────────────
  {
    id: 3014, nome: 'Remada Alta com Barra', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Trapézio, Bíceps',
    equipamento: 'Barra',
    descricao: '1. Em pé, segure a barra com pegada estreita (mãos próximas).\n2. Puxe a barra para cima até a altura do queixo.\n3. Cotovelos apontam para os lados e para cima.\n4. Desça de forma controlada.\n5. Trabalha deltóide lateral e trapézio.',
  },
  {
    id: 3015, nome: 'Remada Alta com Halteres', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Trapézio, Bíceps',
    equipamento: 'Halteres',
    descricao: '1. Em pé, segure um halter em cada mão à frente do corpo.\n2. Puxe os halteres para cima mantendo-os próximos ao corpo.\n3. Cotovelos sobem primeiro, acima das mãos.\n4. Desça de forma controlada.',
  },
  {
    id: 3016, nome: 'Elevação Frontal no Cabo', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Peitoral superior',
    equipamento: 'Polia baixa',
    descricao: '1. De costas para a polia baixa, segure a pegada entre as pernas.\n2. Eleve o braço à frente até a altura dos ombros.\n3. Retorne lentamente.\n4. Tensão constante no deltóide anterior.',
  },
  {
    id: 3017, nome: 'Desenvolvimento no Cabo Sentado', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Tríceps',
    equipamento: 'Cabos',
    descricao: '1. Sente entre duas polias baixas.\n2. Segure as pegadas na altura dos ombros.\n3. Empurre para cima até a extensão.\n4. Retorne de forma controlada.\n5. Tensão constante em todo o arco de movimento.',
  },
  {
    id: 3018, nome: 'Desenvolvimento na Máquina', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Tríceps',
    equipamento: 'Máquina',
    descricao: '1. Sente na máquina com as costas apoiadas.\n2. Segure as pegadas na altura dos ombros.\n3. Empurre para cima até quase estender os braços.\n4. Retorne de forma controlada.\n5. Seguro e ideal para carga pesada.',
  },
  {
    id: 3019, nome: 'Elevação Lateral Sentado com Halteres', grupoMuscular: 'Ombros',
    musculosSecundarios: '',
    equipamento: 'Halteres, Banco',
    descricao: '1. Sente em um banco com um halter em cada mão.\n2. Eleve os braços para os lados até a altura dos ombros.\n3. Cotovelos levemente flexionados.\n4. Desça de forma controlada.\n5. Sentado elimina o impulso do corpo.',
  },
  {
    id: 3020, nome: 'Crucifixo Inverso na Máquina (Pec Deck Invertido)', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Trapézio médio, Rombóides',
    equipamento: 'Máquina Pec Deck',
    descricao: '1. Sente de frente para o encosto da máquina pec deck.\n2. Segure as pegadas e abra os braços para trás.\n3. Aperte as escápulas no final.\n4. Retorne de forma controlada.\n5. Isola o deltóide posterior.',
  },
  {
    id: 3021, nome: 'Elevação Lateral Unilateral no Cabo', grupoMuscular: 'Ombros',
    musculosSecundarios: '',
    equipamento: 'Polia baixa',
    descricao: '1. De lado para a polia baixa, segure a pegada com a mão oposta.\n2. Eleve lateralmente até a altura do ombro.\n3. Retorne de forma controlada.\n4. Tensão constante durante todo o arco.',
  },
  {
    id: 3022, nome: 'W Press com Halteres', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Trapézio, Rotadores',
    equipamento: 'Halteres',
    descricao: '1. Sente segurando halteres com cotovelos a 90° formando um "W".\n2. Empurre para cima convergindo os halteres.\n3. Retorne à posição de "W".\n4. Trabalha todos os feixes do deltóide com rotação externa.',
  },
  {
    id: 3023, nome: 'Battle Ropes (Cordas Navais)', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Core, Braços, Cardio',
    equipamento: 'Cordas navais',
    descricao: '1. Segure uma ponta da corda em cada mão.\n2. Agache levemente e faça ondulações alternadas com os braços.\n3. Mantenha o core contraído e o ritmo constante.\n4. Variações: ondas alternadas, ondas simultâneas, slams.',
  },

  // ─── BÍCEPS (adicionais) ───────────────────────────────────────────────
  {
    id: 4013, nome: 'Rosca Spider (Aranha)', grupoMuscular: 'Bíceps',
    musculosSecundarios: 'Antebraço',
    equipamento: 'Barra EZ, Banco inclinado',
    descricao: '1. Deite de bruços no banco inclinado com os braços pendurados.\n2. Segure a barra EZ e flexione os cotovelos.\n3. Suba até contração máxima.\n4. Desça de forma controlada.\n5. Sem impulso — isola o bíceps na fase de contração.',
  },
  {
    id: 4014, nome: 'Rosca Drag (Arrasto)', grupoMuscular: 'Bíceps',
    musculosSecundarios: 'Braquial',
    equipamento: 'Barra ou Cabos',
    descricao: '1. Em pé, segure a barra próxima ao corpo.\n2. Flexione arrastando a barra pelo corpo (cotovelos vão para trás).\n3. A barra sobe rente ao tronco até o peito.\n4. Desça pelo mesmo caminho.\n5. Enfatiza a cabeça longa do bíceps.',
  },
  {
    id: 4015, nome: 'Rosca Martelo Cross-Body', grupoMuscular: 'Bíceps',
    musculosSecundarios: 'Braquiorradial',
    equipamento: 'Halteres',
    descricao: '1. Em pé, segure um halter em cada mão (pegada neutra).\n2. Flexione um braço cruzando o halter em direção ao ombro oposto.\n3. Alterne os braços.\n4. Trabalha mais o braquiorradial que a rosca martelo normal.',
  },
  {
    id: 4016, nome: 'Rosca Zottman', grupoMuscular: 'Bíceps',
    musculosSecundarios: 'Antebraço',
    equipamento: 'Halteres',
    descricao: '1. Em pé, faça rosca supinada (palmas para cima) subindo.\n2. No topo, gire os pulsos para pegada pronada (palmas para baixo).\n3. Desça com pegada pronada.\n4. Gire novamente para supinada e repita.\n5. Trabalha bíceps na subida e antebraço na descida.',
  },
  {
    id: 4017, nome: 'Rosca na Máquina', grupoMuscular: 'Bíceps',
    musculosSecundarios: '',
    equipamento: 'Máquina',
    descricao: '1. Sente na máquina de bíceps com os braços no suporte.\n2. Flexione os cotovelos puxando a pegada em direção aos ombros.\n3. Retorne de forma controlada.\n4. Isola completamente o bíceps.',
  },
  {
    id: 4018, nome: 'Rosca Concentrada com Cabo', grupoMuscular: 'Bíceps',
    musculosSecundarios: '',
    equipamento: 'Polia baixa',
    descricao: '1. Sente de frente para uma polia baixa.\n2. Apoie o cotovelo na coxa interna.\n3. Flexione o braço puxando a pegada em direção ao ombro.\n4. Retorne de forma controlada.\n5. Tensão constante durante todo o movimento.',
  },
  {
    id: 4019, nome: 'Rosca Martelo Sentado', grupoMuscular: 'Bíceps',
    musculosSecundarios: 'Braquiorradial',
    equipamento: 'Halteres, Banco',
    descricao: '1. Sente em um banco segurando halteres com pegada neutra.\n2. Flexione alternando os braços.\n3. Sem impulso do corpo.\n4. Sentado elimina trapaça e isola melhor o bíceps.',
  },
  {
    id: 4020, nome: 'Rosca com Barra Pegada Larga', grupoMuscular: 'Bíceps',
    musculosSecundarios: 'Antebraço',
    equipamento: 'Barra',
    descricao: '1. Em pé, segure a barra com pegada supinada mais larga que os ombros.\n2. Flexione os cotovelos trazendo a barra aos ombros.\n3. Retorne de forma controlada.\n4. Ênfase na cabeça curta do bíceps.',
  },

  // ─── TRÍCEPS (adicionais) ──────────────────────────────────────────────
  {
    id: 5015, nome: 'Tríceps Francês Sentado com Barra', grupoMuscular: 'Tríceps',
    musculosSecundarios: '',
    equipamento: 'Barra EZ, Banco',
    descricao: '1. Sente segurando a barra EZ acima da cabeça com braços estendidos.\n2. Flexione os cotovelos descendo a barra atrás da cabeça.\n3. Estenda os braços de volta ao topo.\n4. Cotovelos apontam para cima, fixos.',
  },
  {
    id: 5016, nome: 'Tríceps Mergulho na Máquina', grupoMuscular: 'Tríceps',
    musculosSecundarios: 'Peito, Ombros',
    equipamento: 'Máquina',
    descricao: '1. Sente na máquina de dip com as mãos nas pegadas.\n2. Empurre para baixo estendendo os braços.\n3. Retorne de forma controlada.\n4. Permite ajustar a carga com segurança.',
  },
  {
    id: 5017, nome: 'Tríceps Extensão na Máquina', grupoMuscular: 'Tríceps',
    musculosSecundarios: '',
    equipamento: 'Máquina',
    descricao: '1. Sente na máquina de extensão de tríceps.\n2. Posicione os braços no suporte acolchoado.\n3. Estenda os cotovelos empurrando a pegada para baixo.\n4. Retorne de forma controlada.',
  },
  {
    id: 5018, nome: 'Tríceps Pulley Reverso (Pegada Supinada)', grupoMuscular: 'Tríceps',
    musculosSecundarios: '',
    equipamento: 'Polia alta',
    descricao: '1. De frente para a polia alta, segure a barra com palmas para cima.\n2. Cotovelos fixos ao lado do corpo.\n3. Estenda os braços empurrando a barra para baixo.\n4. Retorne de forma controlada.\n5. Ênfase na cabeça medial do tríceps.',
  },
  {
    id: 5019, nome: 'Tríceps Unilateral no Cabo', grupoMuscular: 'Tríceps',
    musculosSecundarios: '',
    equipamento: 'Polia alta',
    descricao: '1. De frente para a polia alta, segure a pegada com uma mão.\n2. Cotovelo fixo ao lado do corpo.\n3. Estenda o braço empurrando para baixo.\n4. Retorne de forma controlada.\n5. Permite corrigir assimetrias.',
  },
  {
    id: 5020, nome: 'Tríceps Testa com Halteres (Alternado)', grupoMuscular: 'Tríceps',
    musculosSecundarios: '',
    equipamento: 'Halteres, Banco',
    descricao: '1. Deite no banco segurando um halter em cada mão acima do peito.\n2. Flexione um cotovelo descendo o halter até a testa.\n3. Estenda de volta e alterne.\n4. Cada braço trabalha independentemente.',
  },
  {
    id: 5021, nome: 'Flexão de Braço com Mãos Juntas (Diamante)', grupoMuscular: 'Tríceps',
    musculosSecundarios: 'Peito',
    equipamento: 'Peso corporal',
    descricao: '1. Posição de flexão com as mãos formando um diamante sob o peito.\n2. Desça controlando até o peito quase tocar as mãos.\n3. Empurre de volta à posição inicial.\n4. Ênfase no tríceps e peitoral interno.',
  },

  // ─── PERNAS (adicionais) ───────────────────────────────────────────────
  {
    id: 6021, nome: 'Agachamento com Barra Baixa (Low Bar)', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos, Lombar',
    equipamento: 'Barra, Pesos',
    descricao: '1. Posicione a barra mais abaixo no trapézio (não no pescoço).\n2. Incline mais o tronco para compensar.\n3. Desça até pelo menos paralelo.\n4. Empurre pelo calcanhar para subir.\n5. Permite cargas mais pesadas que o high bar.',
  },
  {
    id: 6022, nome: 'Step-Up com Halteres', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos',
    equipamento: 'Halteres, Caixa/Banco',
    descricao: '1. Segure halteres e posicione um pé sobre a caixa.\n2. Empurre pelo calcanhar subindo até estender a perna.\n3. Desça de forma controlada com a outra perna.\n4. Complete as repetições de um lado antes de trocar.',
  },
  {
    id: 6023, nome: 'Agachamento Cossaco', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Adutores, Glúteos',
    equipamento: 'Peso corporal ou Halter',
    descricao: '1. Pés bem afastados.\n2. Agache lateralmente sobre uma perna enquanto a outra fica estendida.\n3. Desça o mais profundo possível.\n4. Empurre de volta ao centro e alterne.\n5. Excelente para mobilidade e adutores.',
  },
  {
    id: 6024, nome: 'Leg Press Horizontal na Máquina', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos',
    equipamento: 'Máquina',
    descricao: '1. Sente na máquina de leg press horizontal.\n2. Posicione os pés na plataforma na largura dos ombros.\n3. Empurre a plataforma estendendo as pernas.\n4. Retorne flexionando os joelhos a 90°.',
  },
  {
    id: 6025, nome: 'Avanço Reverso com Halteres', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos',
    equipamento: 'Halteres',
    descricao: '1. Em pé segurando halteres, dê um passo para trás.\n2. Desça até o joelho de trás quase tocar o chão.\n3. Empurre de volta à posição inicial com a perna da frente.\n4. Alterne as pernas.\n5. Menos estresse no joelho que o avanço para frente.',
  },
  {
    id: 6026, nome: 'Agachamento no Hack Machine', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos',
    equipamento: 'Máquina Hack',
    descricao: '1. Encaixe-se na máquina hack com os ombros sob os suportes.\n2. Pés na plataforma na largura dos ombros.\n3. Destrave e desça controladamente.\n4. Empurre para cima até quase estender as pernas.\n5. Isola quadríceps com segurança.',
  },
  {
    id: 6027, nome: 'Levantamento Terra Romeno com Barra', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos, Lombar',
    equipamento: 'Barra',
    descricao: '1. Em pé segurando a barra com braços estendidos.\n2. Empurre o quadril para trás mantendo leve flexão nos joelhos.\n3. Desça a barra ao longo das pernas até sentir o alongamento.\n4. Retorne espremendo os glúteos no topo.\n5. Foco no posterior de coxa.',
  },
  {
    id: 6028, nome: 'Flexão Nórdica de Joelhos', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos',
    equipamento: 'Peso corporal',
    descricao: '1. Ajoelhe com os pés presos (parceiro ou suporte).\n2. Desça o corpo para frente de forma controlada mantendo o quadril estendido.\n3. Desça o máximo que conseguir usando os isquiotibiais para frear.\n4. Retorne ou use as mãos para apoiar.\n5. Exercício avançado para posterior de coxa.',
  },
  {
    id: 6029, nome: 'Sissy Squat', grupoMuscular: 'Pernas',
    musculosSecundarios: '',
    equipamento: 'Peso corporal ou Máquina',
    descricao: '1. Em pé, segure-se em um suporte para equilíbrio.\n2. Fique na ponta dos pés e incline o corpo para trás.\n3. Flexione os joelhos descendo o corpo enquanto os joelhos avançam.\n4. Retorne à posição inicial.\n5. Isola intensamente o quadríceps.',
  },
  {
    id: 6030, nome: 'Prensa de Pernas Sentado (Leg Press Horizontal)', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos',
    equipamento: 'Máquina',
    descricao: '1. Sente na máquina com as costas apoiadas.\n2. Pés na plataforma afastados na largura dos ombros.\n3. Empurre a plataforma estendendo as pernas.\n4. Retorne flexionando os joelhos sem travar.',
  },
  {
    id: 6031, nome: 'Agachamento com Salto', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos, Panturrilha',
    equipamento: 'Peso corporal',
    descricao: '1. Agache até a posição paralela.\n2. Salte explosivamente estendendo todo o corpo.\n3. Aterrisse suavemente voltando à posição de agachamento.\n4. Excelente para potência e explosão das pernas.',
  },
  {
    id: 6032, nome: 'Passada Lateral com Halter', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Adutores, Glúteos',
    equipamento: 'Halteres',
    descricao: '1. Em pé segurando halteres, dê um passo largo para o lado.\n2. Flexione o joelho da perna que avançou.\n3. A outra perna fica estendida.\n4. Empurre de volta à posição inicial.\n5. Trabalha adutores e quadríceps lateral.',
  },

  // ─── PANTURRILHA (adicionais) ──────────────────────────────────────────
  {
    id: 7006, nome: 'Panturrilha Burro (Donkey Calf Raise)', grupoMuscular: 'Panturrilha',
    musculosSecundarios: '',
    equipamento: 'Peso corporal ou Máquina',
    descricao: '1. Incline o tronco apoiando as mãos em um suporte.\n2. Fique na ponta dos pés em uma plataforma elevada.\n3. Suba na ponta dos pés contraindo a panturrilha.\n4. Desça além do nível da plataforma para alongar.\n5. O ângulo do quadril aumenta o estiramento.',
  },
  {
    id: 7007, nome: 'Panturrilha no Cabo', grupoMuscular: 'Panturrilha',
    musculosSecundarios: '',
    equipamento: 'Polia baixa',
    descricao: '1. Fique de frente para a polia baixa com uma barra ou cinto.\n2. Suba na ponta dos pés.\n3. Desça de forma controlada.\n4. Tensão constante do cabo durante todo o movimento.',
  },
  {
    id: 7008, nome: 'Panturrilha no Hack Squat', grupoMuscular: 'Panturrilha',
    musculosSecundarios: '',
    equipamento: 'Máquina Hack',
    descricao: '1. Posicione-se na máquina hack com apenas a ponta dos pés na plataforma.\n2. Destrave e suba na ponta dos pés.\n3. Desça o calcanhar abaixo da plataforma.\n4. Suba novamente contraindo a panturrilha.',
  },
  {
    id: 7009, nome: 'Tibialis Raise (Elevação de Tibial)', grupoMuscular: 'Panturrilha',
    musculosSecundarios: '',
    equipamento: 'Peso corporal',
    descricao: '1. Encoste as costas na parede com os pés a ~30cm dela.\n2. Levante a ponta dos pés mantendo os calcanhares no chão.\n3. Desça de forma controlada.\n4. Fortalece o tibial anterior (parte da frente da canela).',
  },

  // ─── GLÚTEOS (adicionais) ──────────────────────────────────────────────
  {
    id: 8010, nome: 'Hip Thrust na Máquina', grupoMuscular: 'Glúteos',
    musculosSecundarios: 'Posterior de coxa',
    equipamento: 'Máquina de Hip Thrust',
    descricao: '1. Sente na máquina com as costas apoiadas no encosto.\n2. Pés no chão na largura dos ombros.\n3. Empurre o quadril para cima contra a resistência.\n4. Aperte os glúteos no topo.\n5. Desça de forma controlada.',
  },
  {
    id: 8011, nome: 'Cable Pull Through', grupoMuscular: 'Glúteos',
    musculosSecundarios: 'Posterior de coxa, Lombar',
    equipamento: 'Polia baixa, Corda',
    descricao: '1. De costas para a polia baixa, passe a corda entre as pernas.\n2. Incline o tronco à frente com leve flexão nos joelhos.\n3. Estenda o quadril puxando a corda entre as pernas.\n4. Aperte os glúteos no topo.\n5. Excelente para aprender o padrão de hip hinge.',
  },
  {
    id: 8012, nome: 'Ponte de Glúteos no Solo', grupoMuscular: 'Glúteos',
    musculosSecundarios: 'Posterior de coxa, Core',
    equipamento: 'Peso corporal',
    descricao: '1. Deite de costas com joelhos dobrados e pés no chão.\n2. Empurre o quadril para cima espremendo os glúteos.\n3. Forme uma linha reta dos ombros aos joelhos.\n4. Desça de forma controlada.\n5. Pode adicionar peso no quadril para progressão.',
  },
  {
    id: 8013, nome: 'Agachamento Sumô com Barra', grupoMuscular: 'Glúteos',
    musculosSecundarios: 'Adutores, Quadríceps',
    equipamento: 'Barra',
    descricao: '1. Pés bem afastados com pontas viradas para fora.\n2. Barra apoiada no trapézio.\n3. Agache mantendo os joelhos alinhados com os pés.\n4. Empurre de volta à posição inicial.\n5. Ênfase em adutores e glúteos.',
  },
  {
    id: 8014, nome: 'Kickback na Máquina de Glúteos', grupoMuscular: 'Glúteos',
    musculosSecundarios: 'Posterior de coxa',
    equipamento: 'Máquina',
    descricao: '1. Posicione-se na máquina com um pé na plataforma.\n2. Empurre a perna para trás estendendo o quadril.\n3. Aperte o glúteo na contração máxima.\n4. Retorne de forma controlada.',
  },
  {
    id: 8015, nome: 'Reverse Hyper (Hiperextensão Reversa)', grupoMuscular: 'Glúteos',
    musculosSecundarios: 'Posterior de coxa, Lombar',
    equipamento: 'Banco ou Máquina',
    descricao: '1. Deite de bruços em um banco elevado com as pernas penduradas.\n2. Eleve as pernas para trás até ficarem alinhadas com o corpo.\n3. Aperte os glúteos no topo.\n4. Desça de forma controlada.\n5. Fortalece glúteos e lombar.',
  },

  // ─── ABDÔMEN (adicionais) ──────────────────────────────────────────────
  {
    id: 9012, nome: 'Woodchop no Cabo', grupoMuscular: 'Abdômen',
    musculosSecundarios: 'Oblíquos, Ombros',
    equipamento: 'Polia alta ou baixa',
    descricao: '1. Fique de lado para a polia com as duas mãos na pegada.\n2. Puxe diagonalmente de cima para baixo (ou de baixo para cima).\n3. Gire o tronco de forma controlada.\n4. Retorne lentamente.\n5. Excelente para oblíquos e rotação.',
  },
  {
    id: 9013, nome: 'Elevação de Pernas Deitado', grupoMuscular: 'Abdômen',
    musculosSecundarios: 'Flexores do quadril',
    equipamento: 'Peso corporal',
    descricao: '1. Deite de costas com as mãos sob os glúteos.\n2. Pernas estendidas, eleve até 90°.\n3. Desça de forma controlada sem tocar o chão.\n4. Mantenha a lombar pressionada no chão.\n5. Foco no abdômen inferior.',
  },
  {
    id: 9014, nome: 'Dead Bug', grupoMuscular: 'Abdômen',
    musculosSecundarios: 'Core profundo',
    equipamento: 'Peso corporal',
    descricao: '1. Deite de costas com braços estendidos ao teto e joelhos a 90°.\n2. Estenda simultaneamente o braço direito e a perna esquerda.\n3. Retorne e alterne.\n4. Mantenha a lombar pressionada no chão durante todo o movimento.\n5. Excelente para estabilização do core.',
  },
  {
    id: 9015, nome: 'Pallof Press', grupoMuscular: 'Abdômen',
    musculosSecundarios: 'Oblíquos, Core profundo',
    equipamento: 'Cabos ou Elástico',
    descricao: '1. Fique de lado para o cabo na altura do peito.\n2. Segure a pegada com ambas as mãos no centro do peito.\n3. Empurre as mãos para frente resistindo à rotação.\n4. Retorne ao peito.\n5. Exercício anti-rotação para estabilidade do core.',
  },
  {
    id: 9016, nome: 'V-Up', grupoMuscular: 'Abdômen',
    musculosSecundarios: 'Flexores do quadril',
    equipamento: 'Peso corporal',
    descricao: '1. Deite de costas com braços e pernas estendidos.\n2. Eleve simultaneamente o tronco e as pernas formando um "V".\n3. Toque os pés com as mãos no topo.\n4. Retorne de forma controlada.',
  },
  {
    id: 9017, nome: 'Crunch no Cabo em Pé', grupoMuscular: 'Abdômen',
    musculosSecundarios: '',
    equipamento: 'Polia alta',
    descricao: '1. De costas para a polia alta, segure a corda atrás da cabeça.\n2. Flexione o tronco para baixo contraindo o abdômen.\n3. Retorne de forma controlada.\n4. Tensão constante do cabo.',
  },
  {
    id: 9018, nome: 'Abdominal Declinado', grupoMuscular: 'Abdômen',
    musculosSecundarios: '',
    equipamento: 'Banco declinado',
    descricao: '1. Prenda os pés no suporte do banco declinado.\n2. Cruze os braços no peito ou coloque as mãos atrás da cabeça.\n3. Suba o tronco até posição sentada.\n4. Desça de forma controlada.\n5. A declinação aumenta a dificuldade.',
  },
  {
    id: 9019, nome: 'Abdominal na Roda (Ab Wheel)', grupoMuscular: 'Abdômen',
    musculosSecundarios: 'Ombros, Lombar',
    equipamento: 'Roda abdominal',
    descricao: '1. Ajoelhe segurando a roda abdominal no chão.\n2. Role para frente estendendo o corpo o máximo possível.\n3. Puxe de volta à posição inicial usando o abdômen.\n4. Mantenha o core contraído durante todo o movimento.\n5. Exercício avançado.',
  },
  {
    id: 9020, nome: 'Elevação de Joelhos Suspenso', grupoMuscular: 'Abdômen',
    musculosSecundarios: 'Flexores do quadril',
    equipamento: 'Barra fixa',
    descricao: '1. Pendure na barra fixa com braços estendidos.\n2. Flexione os joelhos trazendo-os em direção ao peito.\n3. Desça de forma controlada.\n4. Evite balanço do corpo.\n5. Variação mais fácil da elevação de pernas suspenso.',
  },
  {
    id: 9021, nome: 'Prancha com Toque no Ombro', grupoMuscular: 'Abdômen',
    musculosSecundarios: 'Core, Ombros',
    equipamento: 'Peso corporal',
    descricao: '1. Posição de prancha alta (braços estendidos).\n2. Toque o ombro esquerdo com a mão direita.\n3. Retorne e alterne.\n4. Mantenha o quadril estável sem rotar.\n5. Trabalha estabilidade anti-rotação do core.',
  },

  // ─── ANTEBRAÇO (adicionais) ────────────────────────────────────────────
  {
    id: 10004, nome: 'Rosca de Pulso com Halteres', grupoMuscular: 'Antebraço',
    musculosSecundarios: '',
    equipamento: 'Halteres',
    descricao: '1. Sente com os antebraços apoiados nas coxas segurando halteres.\n2. Pegada supinada (palmas para cima).\n3. Flexione os pulsos para cima.\n4. Desça de forma controlada.\n5. Cada mão trabalha independentemente.',
  },
  {
    id: 10005, nome: 'Dead Hang (Sustentação na Barra)', grupoMuscular: 'Antebraço',
    musculosSecundarios: 'Costas, Ombros',
    equipamento: 'Barra fixa',
    descricao: '1. Pendure na barra fixa com pegada pronada.\n2. Braços estendidos, corpo relaxado.\n3. Segure o máximo de tempo possível.\n4. Ótimo para força de pegada e descompressão da coluna.',
  },
  {
    id: 10006, nome: 'Wrist Roller (Rolo de Pulso)', grupoMuscular: 'Antebraço',
    musculosSecundarios: '',
    equipamento: 'Rolo de pulso',
    descricao: '1. Segure o rolo com braços estendidos à frente.\n2. Enrole a corda girando os pulsos para levantar o peso.\n3. Desenrole de forma controlada.\n4. Trabalha flexores e extensores do antebraço.',
  },
  {
    id: 10007, nome: 'Gripper (Aperto de Mão)', grupoMuscular: 'Antebraço',
    musculosSecundarios: '',
    equipamento: 'Gripper / Hand Grip',
    descricao: '1. Segure o gripper com uma mão.\n2. Feche completamente esmagando as alças.\n3. Abra de forma controlada.\n4. Excelente para força de pegada e grip.',
  },
  {
    id: 10008, nome: 'Rosca de Pulso no Cabo', grupoMuscular: 'Antebraço',
    musculosSecundarios: '',
    equipamento: 'Polia baixa',
    descricao: '1. Sente de frente para a polia baixa com os antebraços nas coxas.\n2. Segure a barra com pegada supinada.\n3. Flexione os pulsos para cima.\n4. Desça de forma controlada.\n5. Tensão constante do cabo.',
  },

  // ─── CARDIO / FUNCIONAIS (adicionais) ──────────────────────────────────
  {
    id: 11008, nome: 'Box Jump (Salto na Caixa)', grupoMuscular: 'Cardio',
    musculosSecundarios: 'Pernas, Glúteos',
    equipamento: 'Caixa pliométrica',
    descricao: '1. Fique de frente para a caixa a uma distância confortável.\n2. Agache levemente e salte para cima da caixa.\n3. Aterrisse suavemente com ambos os pés na caixa.\n4. Fique em pé, desça e repita.',
  },
  {
    id: 11009, nome: 'Escalador (Mountain Climber)', grupoMuscular: 'Cardio',
    musculosSecundarios: 'Abdômen, Ombros, Pernas',
    equipamento: 'Peso corporal',
    descricao: '1. Posição de prancha alta.\n2. Traga um joelho em direção ao peito rapidamente.\n3. Alterne as pernas em ritmo acelerado.\n4. Mantenha o core contraído e o quadril estável.',
  },
  {
    id: 11010, nome: 'Jumping Jack', grupoMuscular: 'Cardio',
    musculosSecundarios: 'Pernas, Ombros',
    equipamento: 'Peso corporal',
    descricao: '1. Em pé, pernas juntas e braços ao lado.\n2. Salte abrindo as pernas e elevando os braços acima da cabeça.\n3. Salte de volta juntando as pernas e baixando os braços.\n4. Repita em ritmo constante.',
  },
  {
    id: 11011, nome: 'Bear Crawl (Caminhada de Urso)', grupoMuscular: 'Cardio',
    musculosSecundarios: 'Core, Ombros, Pernas',
    equipamento: 'Peso corporal',
    descricao: '1. Posição de quatro apoios com joelhos levantados do chão.\n2. Avance mão e pé opostos simultaneamente.\n3. Mantenha as costas retas e o core contraído.\n4. Alterne os lados caminhando para frente.',
  },
  {
    id: 11012, nome: 'Stair Climber (Escada)', grupoMuscular: 'Cardio',
    musculosSecundarios: 'Pernas, Glúteos',
    equipamento: 'Máquina de escada',
    descricao: '1. Suba na máquina e segure levemente as barras laterais.\n2. Suba os degraus em ritmo constante.\n3. Mantenha postura ereta, não se apoie nas barras.\n4. Ajuste velocidade conforme condicionamento.',
  },
  {
    id: 11013, nome: 'Sprint', grupoMuscular: 'Cardio',
    musculosSecundarios: 'Pernas, Glúteos, Core',
    equipamento: 'Nenhum',
    descricao: '1. Corrida em velocidade máxima por distância curta (20-100m).\n2. Braços bombeando ao lado do corpo.\n3. Descanso ativo entre sprints.\n4. Excelente para queima calórica e condicionamento anaeróbico.',
  },
  {
    id: 11014, nome: 'High Knees (Joelhos Altos)', grupoMuscular: 'Cardio',
    musculosSecundarios: 'Abdômen, Flexores do quadril',
    equipamento: 'Peso corporal',
    descricao: '1. Em pé, corra no lugar elevando os joelhos à altura do quadril.\n2. Braços acompanham o movimento como em uma corrida.\n3. Mantenha ritmo acelerado.\n4. Excelente aquecimento e cardio.',
  },
  {
    id: 11015, nome: 'Dumbbell Burpee', grupoMuscular: 'Cardio',
    musculosSecundarios: 'Corpo inteiro',
    equipamento: 'Halteres',
    descricao: '1. Segure halteres, agache e coloque-os no chão.\n2. Salte os pés para trás em posição de prancha.\n3. Faça uma flexão (opcional).\n4. Salte os pés de volta, fique em pé e eleve os halteres acima da cabeça.',
  },

  // ─── TRAPÉZIO ──────────────────────────────────────────────────────────
  {
    id: 12001, nome: 'Encolhimento com Barra por Trás', grupoMuscular: 'Trapézio',
    musculosSecundarios: '',
    equipamento: 'Barra',
    descricao: '1. Em pé, segure a barra atrás do corpo com pegada pronada.\n2. Eleve os ombros em direção às orelhas.\n3. Segure no topo por 1 segundo.\n4. Desça de forma controlada.\n5. Trabalha fibras diferentes do encolhimento frontal.',
  },
  {
    id: 12002, nome: 'Encolhimento no Smith', grupoMuscular: 'Trapézio',
    musculosSecundarios: '',
    equipamento: 'Smith Machine',
    descricao: '1. Fique de frente para a barra do Smith.\n2. Segure com pegada pronada na largura dos ombros.\n3. Eleve os ombros retos para cima (não role).\n4. Desça de forma controlada.',
  },
  {
    id: 12003, nome: 'Face Pull', grupoMuscular: 'Trapézio',
    musculosSecundarios: 'Posterior de ombro, Rombóides',
    equipamento: 'Polia alta, Corda',
    descricao: '1. Posicione a polia na altura da cabeça com corda.\n2. Puxe a corda em direção ao rosto separando as mãos.\n3. Cotovelos altos, aperte as escápulas.\n4. Retorne de forma controlada.\n5. Excelente para saúde dos ombros e postura.',
  },
  {
    id: 12004, nome: 'Encolhimento com Halteres Inclinado', grupoMuscular: 'Trapézio',
    musculosSecundarios: '',
    equipamento: 'Halteres, Banco inclinado',
    descricao: '1. Deite de bruços em banco inclinado segurando halteres.\n2. Eleve os ombros apertando as escápulas.\n3. Segure no topo.\n4. Desça de forma controlada.\n5. Foca no trapézio médio e inferior.',
  },

];

export const GRUPOS_MUSCULARES = [
  'Peito',
  'Costas',
  'Ombros',
  'Bíceps',
  'Tríceps',
  'Pernas',
  'Panturrilha',
  'Glúteos',
  'Abdômen',
  'Antebraço',
  'Trapézio',
  'Cardio',
];
