import type { Exercicio } from '../types/treino';

export const EXERCICIOS_PADRAO: Exercicio[] = [

  // ─── PEITO ───────────────────────────────────────────────────────────────
  {
    id: 1001, nome: 'Supino Reto com Barra', grupoMuscular: 'Peito',
    musculosSecundarios: 'Tríceps, Ombros',
    equipamento: 'Barra, Banco',
    descricao: '1. Deite no banco com os pés apoiados no chão.\n2. Segure a barra com pegada um pouco mais larga que os ombros.\n3. Desça a barra controlando até tocar levemente o peito.\n4. Empurre a barra para cima até os braços ficarem quase estendidos.\n5. Mantenha as escápulas retraídas e o core contraído durante todo o movimento.',
  },
  {
    id: 1002, nome: 'Supino Inclinado com Barra', grupoMuscular: 'Peito',
    musculosSecundarios: 'Tríceps, Ombros',
    equipamento: 'Barra, Banco inclinado',
    descricao: '1. Ajuste o banco a 30–45°.\n2. Segure a barra com pegada larga e desça até a parte superior do peito.\n3. Empurre para cima sem trancar os cotovelos.\n4. Foco na porção superior do peitoral.',
  },
  {
    id: 1003, nome: 'Supino Declinado com Barra', grupoMuscular: 'Peito',
    musculosSecundarios: 'Tríceps',
    equipamento: 'Barra, Banco declinado',
    descricao: '1. Prenda os pés no suporte do banco declinado.\n2. Segure a barra com pegada larga.\n3. Desça a barra até a parte inferior do peito.\n4. Empurre para cima de forma controlada.\n5. Trabalha a porção inferior do peitoral.',
  },
  {
    id: 1004, nome: 'Supino Reto com Halteres', grupoMuscular: 'Peito',
    musculosSecundarios: 'Tríceps, Ombros',
    equipamento: 'Halteres, Banco',
    descricao: '1. Segure um halter em cada mão e deite no banco.\n2. Inicie com os halteres na altura do peito, cotovelos a 45°.\n3. Estenda os braços para cima sem trancá-los.\n4. Retorne de forma controlada, abrindo o peito.\n5. Amplitude maior que o supino com barra.',
  },
  {
    id: 1005, nome: 'Supino Inclinado com Halteres', grupoMuscular: 'Peito',
    musculosSecundarios: 'Ombros, Tríceps',
    equipamento: 'Halteres, Banco inclinado',
    descricao: '1. Ajuste o banco a 30–45°.\n2. Segure um halter em cada mão na altura do peito superior.\n3. Empurre para cima convergindo os halteres levemente.\n4. Desça de forma controlada sentindo o estiramento do peito.',
  },
  {
    id: 1006, nome: 'Crucifixo Reto com Halteres', grupoMuscular: 'Peito',
    musculosSecundarios: 'Ombros',
    equipamento: 'Halteres, Banco',
    descricao: '1. Deite no banco segurando halteres acima do peito, palmas se encarando.\n2. Abra os braços em arco para os lados até sentir o peito esticar.\n3. Mantenha leve flexão nos cotovelos durante todo o movimento.\n4. Retorne os halteres para cima fechando o arco.',
  },
  {
    id: 1007, nome: 'Crucifixo Inclinado com Halteres', grupoMuscular: 'Peito',
    musculosSecundarios: 'Ombros',
    equipamento: 'Halteres, Banco inclinado',
    descricao: '1. Banco a 30–45°.\n2. Execute o movimento de crucifixo focando na porção superior do peitoral.\n3. Controle a descida sentindo o estiramento.\n4. Feche o arco no topo espremendo o peito.',
  },
  {
    id: 1008, nome: 'Crossover no Cabo', grupoMuscular: 'Peito',
    musculosSecundarios: 'Ombros',
    equipamento: 'Cabo cruzado',
    descricao: '1. Ajuste as polias na altura dos ombros ou acima.\n2. Fique no centro e segure as alças com os braços abertos.\n3. Puxe as alças em arco, cruzando as mãos na frente do corpo.\n4. Esprema o peito no ponto de cruzamento.\n5. Retorne controlando a abertura.',
  },
  {
    id: 1009, nome: 'Pec Deck (Voador)', grupoMuscular: 'Peito',
    musculosSecundarios: 'Ombros',
    equipamento: 'Máquina',
    descricao: '1. Ajuste o assento para que os cotovelos fiquem na altura dos ombros.\n2. Apoie os antebraços nas almofadas ou segure as alças.\n3. Feche os braços à frente do corpo espremendo o peito.\n4. Retorne de forma controlada sem deixar o peso bater.',
  },
  {
    id: 1010, nome: 'Flexão de Braço', grupoMuscular: 'Peito',
    musculosSecundarios: 'Tríceps, Ombros, Core',
    equipamento: 'Peso corporal',
    descricao: '1. Posição de prancha com mãos levemente mais largas que os ombros.\n2. Desça o corpo mantendo-o reto, cotovelos a 45° do tronco.\n3. Toque levemente o peito ou quase no chão.\n4. Empurre de volta à posição inicial.\n5. Não deixe o quadril cair.',
  },
  {
    id: 1011, nome: 'Mergulho em Paralelas (Peito)', grupoMuscular: 'Peito',
    musculosSecundarios: 'Tríceps, Ombros',
    equipamento: 'Paralelas',
    descricao: '1. Segure as paralelas e suba com os braços estendidos.\n2. Incline o tronco levemente para frente para focar no peito.\n3. Desça dobrando os cotovelos para os lados até sentir o peito esticar.\n4. Empurre de volta sem trancar os cotovelos.',
  },
  {
    id: 1012, nome: 'Pullover com Halter', grupoMuscular: 'Peito',
    musculosSecundarios: 'Costas, Tríceps',
    equipamento: 'Halter, Banco',
    descricao: '1. Deite transversalmente no banco com apenas as escápulas apoiadas.\n2. Segure um halter com as duas mãos acima do peito.\n3. Abaixe o halter em arco atrás da cabeça mantendo leve flexão nos cotovelos.\n4. Retorne para a posição inicial espremendo o peito.',
  },
  {
    id: 1013, nome: 'Supino Declinado com Halteres', grupoMuscular: 'Peito',
    musculosSecundarios: 'Tríceps',
    equipamento: 'Halteres, Banco declinado',
    descricao: '1. Prenda os pés no suporte do banco declinado.\n2. Segure um halter em cada mão na altura do peito inferior.\n3. Empurre para cima sem travar os cotovelos.\n4. Amplitude maior que com barra — explore o estiramento.\n5. Foco na porção inferior do peitoral.',
  },
  {
    id: 1014, nome: 'Crucifixo no Cabo (Polia)', grupoMuscular: 'Peito',
    musculosSecundarios: 'Ombros',
    equipamento: 'Cabo cruzado',
    descricao: '1. Ajuste as polias na altura dos ombros.\n2. Segure as alças com leve flexão nos cotovelos, tronco levemente inclinado.\n3. Feche os braços em arco à frente do corpo, convergindo as mãos.\n4. Esprema o peito no ponto de encontro.\n5. Retorne controlando a abertura. Tensão constante durante todo o movimento.',
  },
  {
    id: 1015, nome: 'Flexão Inclinada (pés elevados)', grupoMuscular: 'Peito',
    musculosSecundarios: 'Tríceps, Ombros',
    equipamento: 'Banco',
    descricao: '1. Apoie os pés em um banco e as mãos no chão.\n2. Corpo inclinado, foco na porção superior do peitoral.\n3. Desça o peito em direção ao chão, cotovelos a 45°.\n4. Empurre de volta à posição inicial.\n5. Quanto mais elevados os pés, maior a ativação do peito superior.',
  },
  {
    id: 1016, nome: 'Flexão de Braço Fechada', grupoMuscular: 'Peito',
    musculosSecundarios: 'Tríceps',
    equipamento: 'Peso corporal',
    descricao: '1. Posição de flexão com as mãos na largura dos ombros ou mais próximas.\n2. Desça mantendo os cotovelos junto ao corpo.\n3. Foco no peito interno e tríceps.\n4. Empurre de volta à posição inicial com controle.',
  },

  // ─── COSTAS ──────────────────────────────────────────────────────────────
  {
    id: 2001, nome: 'Puxada Frontal na Polia', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps, Romboides',
    equipamento: 'Polia alta',
    descricao: '1. Sente na máquina e segure a barra com pegada pronada (larga).\n2. Incline levemente o tronco para trás.\n3. Puxe a barra em direção à parte superior do peito.\n4. Esprema as costas no final do movimento.\n5. Retorne controlando o peso até quase a extensão completa.',
  },
  {
    id: 2002, nome: 'Puxada Pegada Fechada', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps',
    equipamento: 'Polia alta',
    descricao: '1. Use o triângulo ou a barra com pegada neutra próxima.\n2. Mantenha o tronco ereto e puxe em direção ao abdômen superior.\n3. Abra os cotovelos para trás apertando as costas.\n4. Retorne de forma controlada.',
  },
  {
    id: 2003, nome: 'Remada Curvada com Barra', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps, Lombar',
    equipamento: 'Barra',
    descricao: '1. Segure a barra com pegada pronada, tronco inclinado a 45°.\n2. Puxe a barra em direção ao abdômen mantendo as costas retas.\n3. Retraia as escápulas no topo do movimento.\n4. Desça de forma controlada sem deixar os braços pendurar.',
  },
  {
    id: 2004, nome: 'Remada Unilateral com Halter', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps',
    equipamento: 'Halter, Banco',
    descricao: '1. Apoie um joelho e a mão no banco.\n2. Com a outra mão segure o halter com o braço estendido.\n3. Puxe o halter em direção ao quadril, abrindo o cotovelo para trás.\n4. Esprema as costas no topo.\n5. Retorne lentamente até o braço esticar.',
  },
  {
    id: 2005, nome: 'Remada na Polia Baixa', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps, Romboides',
    equipamento: 'Polia baixa',
    descricao: '1. Sente no banco com os pés no apoio e segure o triângulo.\n2. Mantenha as costas eretas e puxe em direção ao abdômen.\n3. Abra os cotovelos para trás, retraindo as escápulas.\n4. Retorne com controle, estirando as costas.',
  },
  {
    id: 2006, nome: 'Remada Cavalinho (T-Bar)', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps, Lombar',
    equipamento: 'Barra T ou máquina',
    descricao: '1. Posicione-se sobre a barra com os pés na largura dos ombros.\n2. Agarre as alças e incline o tronco a ~45°.\n3. Puxe a barra em direção ao peito retraindo bem as escápulas.\n4. Retorne com controle.',
  },
  {
    id: 2007, nome: 'Levantamento Terra', grupoMuscular: 'Costas',
    musculosSecundarios: 'Glúteos, Pernas, Trapézio',
    equipamento: 'Barra',
    descricao: '1. Posicione os pés na largura dos ombros com a barra sobre os pés.\n2. Agache segurando a barra com pegada pronada ou mista.\n3. Peito para fora, lombar neutra, core contraído.\n4. Empurre o chão com os pés e suba, estendendo quadril e joelhos juntos.\n5. Retorne com controle.\n⚠️ Jamais arredonde a lombar.',
  },
  {
    id: 2008, nome: 'Barra Fixa (Pegada Pronada)', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps',
    equipamento: 'Barra fixa',
    descricao: '1. Segure a barra com pegada pronada (palmas para frente), mais larga que os ombros.\n2. Pendure com os braços quase estendidos.\n3. Puxe o corpo para cima até o queixo ultrapassar a barra.\n4. Desça lentamente em 3–4 segundos.',
  },
  {
    id: 2009, nome: 'Barra Fixa (Pegada Supinada)', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps',
    equipamento: 'Barra fixa',
    descricao: '1. Segure a barra com pegada supinada (palmas para você), largura dos ombros.\n2. Puxe o corpo para cima focando nos bíceps e costas.\n3. Maior envolvimento do bíceps em relação à pegada pronada.\n4. Desça de forma controlada.',
  },
  {
    id: 2010, nome: 'Hiperextensão Lombar', grupoMuscular: 'Costas',
    musculosSecundarios: 'Glúteos, Posterior de coxa',
    equipamento: 'Banco romano',
    descricao: '1. Posicione-se no banco romano com os quadris na almofada e pés presos.\n2. Cruce os braços no peito ou coloque atrás da cabeça.\n3. Incline o tronco para baixo de forma controlada.\n4. Suba até o corpo ficar alinhado, espremendo glúteos e lombar.\n5. Não hiperextenda além da linha natural.',
  },
  {
    id: 2011, nome: 'Puxada no Pulley Alto', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps',
    equipamento: 'Polia alta',
    descricao: '1. Segure a barra com pegada pronada na largura dos ombros.\n2. Com os braços estendidos, puxe a barra até o queixo.\n3. Mantenha os cotovelos apontando para baixo.\n4. Retorne com controle.',
  },
  {
    id: 2012, nome: 'Serrote com Halter', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps',
    equipamento: 'Halter',
    descricao: '1. Com o tronco quase paralelo ao chão, segure um halter.\n2. Puxe o halter em direção ao quadril como se fosse puxar uma corda de serra.\n3. Retraia bem a escápula no topo.\n4. Alterne os lados.',
  },
  {
    id: 2013, nome: 'Remada Curvada com Halteres', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps, Lombar',
    equipamento: 'Halteres',
    descricao: '1. Com um halter em cada mão, incline o tronco a 45°.\n2. Puxe ambos os halteres simultaneamente em direção ao abdômen.\n3. Retraia as escápulas no topo do movimento.\n4. Maior amplitude e liberdade de movimento comparado à barra.\n5. Desça controlando até os braços estenderem.',
  },
  {
    id: 2014, nome: 'Remada na Máquina (Chest Supported)', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps, Romboides',
    equipamento: 'Máquina',
    descricao: '1. Ajuste o banco e apoie o peito na almofada.\n2. Segure as alças e puxe em direção ao corpo.\n3. O apoio no peito elimina a compensação com a lombar.\n4. Ótima opção para isolar as costas com segurança.\n5. Esprema as escápulas no final.',
  },
  {
    id: 2015, nome: 'Puxada na Polia com Pegada Neutra', grupoMuscular: 'Costas',
    musculosSecundarios: 'Bíceps',
    equipamento: 'Polia alta, triângulo',
    descricao: '1. Use o triângulo ou barra V na polia alta.\n2. Sente com os pés firmes e incline levemente o tronco para trás.\n3. Puxe o triângulo até a frente do peito, cotovelos apontando para baixo.\n4. Esprema as costas no final e retorne com controle.',
  },

  // ─── OMBROS ──────────────────────────────────────────────────────────────
  {
    id: 3001, nome: 'Desenvolvimento Militar com Barra', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Tríceps, Trapézio',
    equipamento: 'Barra',
    descricao: '1. Segure a barra na frente, na altura dos ombros, com pegada larga.\n2. Empurre a barra para cima até os braços ficarem estendidos.\n3. Desça controlando até a linha do queixo.\n4. Mantenha o core rígido, sem arquear a lombar.',
  },
  {
    id: 3002, nome: 'Desenvolvimento com Halteres', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Tríceps',
    equipamento: 'Halteres',
    descricao: '1. Sente com as costas apoiadas ou em pé.\n2. Segure um halter em cada mão na altura dos ombros, cotovelos a 90°.\n3. Empurre os halteres para cima convergindo levemente.\n4. Retorne à posição inicial de forma controlada.',
  },
  {
    id: 3003, nome: 'Elevação Lateral com Halteres', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Trapézio',
    equipamento: 'Halteres',
    descricao: '1. Em pé, segure um halter em cada mão ao lado do corpo.\n2. Levante os braços para os lados até a altura dos ombros (cotovelos levemente flexionados).\n3. Pense em derramar água com o polegar levemente para baixo.\n4. Desça lentamente (3 segundos).',
  },
  {
    id: 3004, nome: 'Elevação Frontal com Halteres', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Peito',
    equipamento: 'Halteres',
    descricao: '1. Em pé, segure os halteres à frente das coxas.\n2. Levante um halter de cada vez (ou ambos) até a altura dos ombros.\n3. Mantenha leve flexão nos cotovelos.\n4. Desça de forma controlada.',
  },
  {
    id: 3005, nome: 'Elevação Lateral na Polia', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Trapézio',
    equipamento: 'Polia baixa',
    descricao: '1. Ajuste a polia na posição mais baixa.\n2. Fique de lado e puxe a alça cruzando o corpo.\n3. Levante o braço lateralmente até a altura dos ombros.\n4. Retorne com tensão constante no cabo.',
  },
  {
    id: 3006, nome: 'Crucifixo Inverso com Halteres', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Romboides, Trapézio',
    equipamento: 'Halteres',
    descricao: '1. Incline o tronco a 45–90° para frente.\n2. Segure os halteres com palmas se encarando.\n3. Abra os braços para os lados até a altura dos ombros.\n4. Esprema as escápulas no topo.\n5. Desça de forma controlada.',
  },
  {
    id: 3007, nome: 'Encolhimento de Ombros com Barra', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Trapézio',
    equipamento: 'Barra',
    descricao: '1. Segure a barra na frente com os braços estendidos.\n2. Encolha os ombros em direção às orelhas o máximo possível.\n3. Mantenha por 1 segundo espremendo o trapézio.\n4. Retorne de forma controlada.\n5. Não gire os ombros.',
  },
  {
    id: 3008, nome: 'Encolhimento de Ombros com Halteres', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Trapézio',
    equipamento: 'Halteres',
    descricao: '1. Em pé, com um halter em cada mão ao lado do corpo.\n2. Encolha os ombros para cima, espremendo o trapézio.\n3. Segure 1 segundo no topo e desça de forma controlada.',
  },
  {
    id: 3009, nome: 'Face Pull na Polia', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Romboides, Manguito Rotador',
    equipamento: 'Polia alta, corda',
    descricao: '1. Ajuste a polia na altura da cabeça e use a corda.\n2. Puxe a corda em direção ao rosto, separando as mãos.\n3. Os cotovelos devem ficar acima dos ombros no final.\n4. Retorne com controle. Excelente para saúde do ombro.',
  },
  {
    id: 3010, nome: 'Desenvolvimento Arnold', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Tríceps, Trapézio',
    equipamento: 'Halteres',
    descricao: '1. Sente com os halteres na altura dos ombros, palmas voltadas para você.\n2. Ao empurrar para cima, gire os pulsos de forma que as palmas fiquem para fora no topo.\n3. Desça revertendo a rotação.\n4. Movimento completo envolvendo toda a cabeça do deltóide.',
  },
  {
    id: 3011, nome: 'Elevação Frontal com Barra', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Peito',
    equipamento: 'Barra',
    descricao: '1. Em pé, segure a barra com pegada pronada na largura dos ombros.\n2. Levante a barra à frente até a altura dos ombros com leve flexão nos cotovelos.\n3. Mantenha o tronco estável, sem balançar.\n4. Desça lentamente em 3 segundos.',
  },
  {
    id: 3012, nome: 'Desenvolvimento no Smith', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Tríceps',
    equipamento: 'Smith',
    descricao: '1. Ajuste o banco abaixo da barra do Smith.\n2. Posicione a barra na altura dos ombros, pegada pronada larga.\n3. Empurre para cima até os braços ficarem estendidos.\n4. Retorne até a linha do queixo.\n5. O Smith oferece mais estabilidade para quem está aprendendo.',
  },
  {
    id: 3013, nome: 'Elevação Lateral na Máquina', grupoMuscular: 'Ombros',
    musculosSecundarios: 'Trapézio',
    equipamento: 'Máquina',
    descricao: '1. Sente na máquina com os cotovelos apoiados nas almofadas laterais.\n2. Eleve os braços lateralmente contra a resistência.\n3. Pare na altura dos ombros.\n4. Retorne lentamente. Tensão constante durante todo o movimento.',
  },

  // ─── BÍCEPS ──────────────────────────────────────────────────────────────
  {
    id: 4001, nome: 'Rosca Direta com Barra', grupoMuscular: 'Bíceps',
    musculosSecundarios: 'Antebraço',
    equipamento: 'Barra',
    descricao: '1. Em pé, segure a barra com pegada supinada na largura dos ombros.\n2. Mantenha os cotovelos fixos ao lado do corpo.\n3. Curl a barra até os bíceps contraírem totalmente.\n4. Desça lentamente (3 segundos) até a extensão quase completa.',
  },
  {
    id: 4002, nome: 'Rosca Alternada com Halteres', grupoMuscular: 'Bíceps',
    musculosSecundarios: 'Antebraço',
    equipamento: 'Halteres',
    descricao: '1. Em pé, com um halter em cada mão, braços ao lado do corpo.\n2. Curl um halter de cada vez, supinando o punho na subida.\n3. Esprema o bíceps no topo.\n4. Desça antes de subir o outro lado.',
  },
  {
    id: 4003, nome: 'Rosca Martelo com Halteres', grupoMuscular: 'Bíceps',
    musculosSecundarios: 'Braquiorradial, Antebraço',
    equipamento: 'Halteres',
    descricao: '1. Segure os halteres com pegada neutra (palmas se encarando).\n2. Curl os halteres sem girar os pulsos.\n3. Trabalha o braquiorradial e a parte longa do bíceps.\n4. Desça de forma controlada.',
  },
  {
    id: 4004, nome: 'Rosca Concentrada', grupoMuscular: 'Bíceps',
    musculosSecundarios: '',
    equipamento: 'Halter',
    descricao: '1. Sente em um banco com as pernas abertas.\n2. Apoie o cotovelo na parte interna da coxa.\n3. Curl o halter focando em isolar o bíceps.\n4. Esprema bem no topo antes de descer.',
  },
  {
    id: 4005, nome: 'Rosca no Cabo (Polia Baixa)', grupoMuscular: 'Bíceps',
    musculosSecundarios: 'Antebraço',
    equipamento: 'Polia baixa',
    descricao: '1. Ajuste a polia na posição baixa.\n2. Segure a barra reta ou alça e curl para cima.\n3. Tensão constante no bíceps durante todo o movimento.\n4. Ótima opção para o pico do bíceps.',
  },
  {
    id: 4006, nome: 'Rosca Scott com Barra', grupoMuscular: 'Bíceps',
    musculosSecundarios: 'Antebraço',
    equipamento: 'Barra, Banco Scott',
    descricao: '1. Apoie a parte de trás dos braços no banco inclinado.\n2. Segure a barra com pegada supinada.\n3. Curl até os bíceps estarem totalmente contraídos.\n4. Desça lentamente até quase a extensão completa (não trave totalmente).',
  },
  {
    id: 4007, nome: 'Rosca Inclinada com Halteres', grupoMuscular: 'Bíceps',
    musculosSecundarios: '',
    equipamento: 'Halteres, Banco inclinado',
    descricao: '1. Sente em um banco inclinado a 45–60°.\n2. Com os braços pendurados, curl os halteres supinando os punhos.\n3. A inclinação proporciona maior estiramento na descida.\n4. Excelente para o comprimento do bíceps.',
  },
  {
    id: 4008, nome: 'Rosca Inversa com Barra', grupoMuscular: 'Bíceps',
    musculosSecundarios: 'Braquiorradial, Antebraço',
    equipamento: 'Barra',
    descricao: '1. Segure a barra com pegada pronada (palmas para baixo).\n2. Curl a barra até a altura do queixo.\n3. Mantém mais os antebraços e o braquiorradial.\n4. Desça de forma lenta e controlada.',
  },
  {
    id: 4009, nome: 'Rosca Direta com Barra EZ', grupoMuscular: 'Bíceps',
    musculosSecundarios: 'Antebraço',
    equipamento: 'Barra EZ',
    descricao: '1. Segure a barra EZ nas empunhaduras inclinadas com pegada supinada.\n2. Cotovelos fixos ao lado do corpo.\n3. Curl a barra até os bíceps contraírem totalmente.\n4. Desça lentamente.\n5. Reduz o estresse nos pulsos comparado à barra reta.',
  },
  {
    id: 4010, nome: 'Rosca Scott com Halteres', grupoMuscular: 'Bíceps',
    musculosSecundarios: 'Antebraço',
    equipamento: 'Halteres, Banco Scott',
    descricao: '1. Apoie os braços no banco Scott inclinado.\n2. Segure um halter em cada mão com pegada supinada.\n3. Curl alternado ou simultâneo até a contração total.\n4. Desça lentamente até quase a extensão.\n5. Maior isolamento que a rosca livre.',
  },
  {
    id: 4011, nome: 'Rosca 21', grupoMuscular: 'Bíceps',
    musculosSecundarios: 'Antebraço',
    equipamento: 'Barra ou Halteres',
    descricao: 'Série de 21 repetições dividida em 3 partes:\n1. 7 reps da metade inferior (0° a 90°).\n2. 7 reps da metade superior (90° até o topo).\n3. 7 reps completas (amplitude total).\n4. Sem pausa entre as partes. Excelente para pump no bíceps.',
  },
  {
    id: 4012, nome: 'Rosca Martelo na Polia (Corda)', grupoMuscular: 'Bíceps',
    musculosSecundarios: 'Braquiorradial, Antebraço',
    equipamento: 'Polia baixa, corda',
    descricao: '1. Ajuste a polia na posição baixa e use a corda.\n2. Segure as pontas da corda com pegada neutra (palmas se encarando).\n3. Curl a corda até o pescoço mantendo os cotovelos fixos.\n4. Retorne com controle. Ótimo para o braquiorradial.',
  },

  // ─── TRÍCEPS ─────────────────────────────────────────────────────────────
  {
    id: 5001, nome: 'Tríceps Pulley (Cabo)', grupoMuscular: 'Tríceps',
    musculosSecundarios: '',
    equipamento: 'Polia alta',
    descricao: '1. Ajuste a polia na posição alta com a barra reta ou V.\n2. Fique de frente à polia, cotovelos fixos ao lado do corpo.\n3. Empurre a barra para baixo até estender completamente os braços.\n4. Retorne lentamente sem levantar os cotovelos.',
  },
  {
    id: 5002, nome: 'Tríceps Testa com Barra', grupoMuscular: 'Tríceps',
    musculosSecundarios: '',
    equipamento: 'Barra, Banco',
    descricao: '1. Deite no banco segurando a barra com pegada pronada, braços estendidos.\n2. Dobre apenas os cotovelos abaixando a barra em direção à testa.\n3. Suba estendendo os braços sem mover os cotovelos.\n4. Controle total para não bater na testa.',
  },
  {
    id: 5003, nome: 'Tríceps Francês com Halter', grupoMuscular: 'Tríceps',
    musculosSecundarios: '',
    equipamento: 'Halter',
    descricao: '1. Em pé ou sentado, segure um halter com as duas mãos acima da cabeça.\n2. Dobre os cotovelos abaixando o halter atrás da cabeça.\n3. Suba estendendo os braços, mantendo os cotovelos apontando para cima.\n4. Ótimo para a cabeça longa do tríceps.',
  },
  {
    id: 5004, nome: 'Tríceps Coice com Halter', grupoMuscular: 'Tríceps',
    musculosSecundarios: '',
    equipamento: 'Halter',
    descricao: '1. Incline o tronco a 45°, apoiado no banco ou livre.\n2. Com o braço dobrado a 90° ao lado do corpo, estenda o antebraço para trás.\n3. Esprema o tríceps no final.\n4. Retorne lentamente.',
  },
  {
    id: 5005, nome: 'Mergulho em Paralelas (Tríceps)', grupoMuscular: 'Tríceps',
    musculosSecundarios: 'Peito, Ombros',
    equipamento: 'Paralelas',
    descricao: '1. Suba nas paralelas com os braços estendidos.\n2. Mantenha o tronco ereto (foco no tríceps).\n3. Desça dobrando os cotovelos para trás até 90°.\n4. Suba empurrando, espremendo o tríceps no topo.',
  },
  {
    id: 5006, nome: 'Tríceps no Banco', grupoMuscular: 'Tríceps',
    musculosSecundarios: 'Ombros',
    equipamento: 'Banco',
    descricao: '1. Apoie as mãos na borda de um banco atrás de você.\n2. Mantenha as pernas estendidas (mais difícil) ou dobradas.\n3. Desça dobrando os cotovelos até 90°.\n4. Empurre de volta à posição inicial.',
  },
  {
    id: 5007, nome: 'Tríceps Corda no Cabo', grupoMuscular: 'Tríceps',
    musculosSecundarios: '',
    equipamento: 'Polia alta, corda',
    descricao: '1. Use a corda no cabo alto.\n2. Segure as pontas da corda e empurre para baixo.\n3. Ao final, abra as mãos para os lados para maximizar a contração.\n4. Retorne lentamente.',
  },
  {
    id: 5008, nome: 'Supino Fechado', grupoMuscular: 'Tríceps',
    musculosSecundarios: 'Peito, Ombros',
    equipamento: 'Barra, Banco',
    descricao: '1. Deite no banco com a barra acima do peito.\n2. Use pegada pronada com as mãos na largura dos ombros ou mais próximas.\n3. Desça a barra ao peito baixo.\n4. Empurre focando em usar o tríceps.',
  },
  {
    id: 5009, nome: 'Tríceps Testa com Halteres', grupoMuscular: 'Tríceps',
    musculosSecundarios: '',
    equipamento: 'Halteres, Banco',
    descricao: '1. Deite no banco segurando um halter em cada mão, braços estendidos acima do peito.\n2. Dobre apenas os cotovelos abaixando os halteres em direção às têmporas/testa.\n3. Os cotovelos ficam fixos apontando para o teto.\n4. Estenda os braços voltando à posição inicial.\n5. Maior amplitude de movimento comparado à barra — explora melhor o estiramento.',
  },
  {
    id: 5010, nome: 'Tríceps Testa na Polia', grupoMuscular: 'Tríceps',
    musculosSecundarios: '',
    equipamento: 'Polia baixa, barra reta',
    descricao: '1. Ajuste a polia na posição mais baixa com a barra reta ou EZ.\n2. Deite no banco posicionado atrás da polia.\n3. Segure a barra com os braços estendidos apontando para a polia.\n4. Dobre os cotovelos abaixando a barra em direção à testa.\n5. Tensão constante no tríceps graças ao cabo. Ótima variação para a porção longa.',
  },
  {
    id: 5011, nome: 'Tríceps Francês com Barra EZ', grupoMuscular: 'Tríceps',
    musculosSecundarios: '',
    equipamento: 'Barra EZ',
    descricao: '1. Em pé ou sentado, segure a barra EZ com os braços estendidos acima da cabeça.\n2. Dobre os cotovelos abaixando a barra atrás da cabeça.\n3. Cotovelos apontados para o teto durante todo o movimento.\n4. Suba estendendo os braços.\n5. A barra EZ reduz o estresse nos pulsos.',
  },
  {
    id: 5012, nome: 'Tríceps Francês na Polia', grupoMuscular: 'Tríceps',
    musculosSecundarios: '',
    equipamento: 'Polia alta, corda',
    descricao: '1. Ajuste a polia alta e use a corda.\n2. De costas para a máquina, segure a corda atrás da cabeça com os cotovelos dobrados.\n3. Estenda os braços para frente empurrando a corda.\n4. Retorne lentamente dobrando os cotovelos atrás da cabeça.\n5. Tensão constante na cabeça longa do tríceps.',
  },
  {
    id: 5013, nome: 'Tríceps Coice na Polia', grupoMuscular: 'Tríceps',
    musculosSecundarios: '',
    equipamento: 'Polia baixa',
    descricao: '1. Ajuste a polia baixa e prenda a alça.\n2. Incline o tronco a 45° com o braço dobrado a 90°.\n3. Estenda o antebraço para trás contra a resistência do cabo.\n4. Esprema o tríceps na extensão completa.\n5. Tensão constante diferente do halter — sem perda de resistência no topo.',
  },
  {
    id: 5014, nome: 'Tríceps Pulley com V Bar', grupoMuscular: 'Tríceps',
    musculosSecundarios: '',
    equipamento: 'Polia alta, V bar',
    descricao: '1. Use o V bar (triângulo) na polia alta.\n2. Fique de frente, cotovelos fixos ao lado do corpo.\n3. Empurre o V bar para baixo até estender completamente os braços.\n4. Retorne lentamente sem levantar os cotovelos.\n5. A pegada neutra do V bar reduz estresse nos pulsos.',
  },

  // ─── PERNAS ──────────────────────────────────────────────────────────────
  {
    id: 6001, nome: 'Agachamento Livre com Barra', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos, Lombar, Core',
    equipamento: 'Barra, Rack',
    descricao: '1. Barra sobre a parte superior das costas, pés na largura dos ombros.\n2. Empurre os joelhos para fora na mesma direção dos dedos.\n3. Desça até a coxa ficar paralela (ou abaixo) ao chão.\n4. Mantenha o peito ereto e a lombar neutra.\n5. Suba empurrando o chão com os pés.',
  },
  {
    id: 6002, nome: 'Leg Press 45°', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos',
    equipamento: 'Máquina Leg Press',
    descricao: '1. Sente na máquina com os pés na plataforma na largura dos ombros.\n2. Solte as travas e dobre os joelhos até ~90°.\n3. Empurre a plataforma de volta sem travar os joelhos no topo.\n4. Pés mais altos = mais glúteos; mais baixos = mais quadríceps.',
  },
  {
    id: 6003, nome: 'Extensão de Joelhos (Cadeira Extensora)', grupoMuscular: 'Pernas',
    musculosSecundarios: '',
    equipamento: 'Máquina',
    descricao: '1. Sente na máquina com os joelhos dobrados a 90° ou menos.\n2. Estenda as pernas até quase a extensão total.\n3. Segure 1 segundo espremendo o quadríceps.\n4. Retorne lentamente em 3–4 segundos.',
  },
  {
    id: 6004, nome: 'Flexão de Joelhos (Mesa Flexora)', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos',
    equipamento: 'Máquina',
    descricao: '1. Deite de bruços com os tornozelos sob o apoio da máquina.\n2. Dobre os joelhos puxando os calcanhares em direção aos glúteos.\n3. Esprema o posterior de coxa no topo.\n4. Desça lentamente.',
  },
  {
    id: 6005, nome: 'Agachamento Hack', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos',
    equipamento: 'Máquina Hack Squat',
    descricao: '1. Posicione-se na máquina com os ombros sob as almofadas.\n2. Pés na largura dos ombros na plataforma.\n3. Desça até a coxa ficar paralela ou abaixo.\n4. Suba empurrando com os calcanhares.',
  },
  {
    id: 6006, nome: 'Avanço (Lunges) com Halteres', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos, Core',
    equipamento: 'Halteres',
    descricao: '1. Em pé com um halter em cada mão.\n2. Dê um passo largo para frente.\n3. Desça até o joelho traseiro quase tocar o chão.\n4. O joelho da frente não deve ultrapassar muito os dedos dos pés.\n5. Suba e alterne as pernas.',
  },
  {
    id: 6007, nome: 'Stiff com Barra', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos, Lombar',
    equipamento: 'Barra',
    descricao: '1. Em pé segurando a barra à frente, pernas levemente dobradas.\n2. Incline o tronco para frente empurrando o quadril para trás.\n3. Desça a barra próxima às pernas até sentir o posterior de coxa esticar.\n4. Suba contraindo o posterior e os glúteos.',
  },
  {
    id: 6008, nome: 'Agachamento Goblet com Halter', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Core, Glúteos',
    equipamento: 'Halter ou Kettlebell',
    descricao: '1. Segure um halter verticalmente na frente do peito.\n2. Pés levemente mais abertos que os ombros, dedos apontando para fora.\n3. Desça em agachamento profundo mantendo o tronco ereto.\n4. Suba empurrando o chão.',
  },
  {
    id: 6009, nome: 'Passada com Barra', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos, Core',
    equipamento: 'Barra',
    descricao: '1. Barra sobre os ombros como no agachamento.\n2. Dê um passo largo alternando as pernas.\n3. Desça até o joelho traseiro quase tocar o chão.\n4. Mantenha o tronco ereto durante todo o movimento.',
  },
  {
    id: 6010, nome: 'Agachamento Búlgaro', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos, Core',
    equipamento: 'Halteres ou Barra, Banco',
    descricao: '1. Apoie o pé de trás em um banco atrás de você.\n2. O pé da frente fica à frente do corpo.\n3. Desça dobrando o joelho da frente até 90°.\n4. Suba empurrando com o calcanhar da frente.',
  },
  {
    id: 6011, nome: 'Cadeira Adutora', grupoMuscular: 'Pernas',
    musculosSecundarios: '',
    equipamento: 'Máquina',
    descricao: '1. Sente com as pernas abertas nas almofadas externas.\n2. Feche as pernas contra a resistência da máquina.\n3. Esprema os adutores no final.\n4. Retorne lentamente.',
  },
  {
    id: 6012, nome: 'Cadeira Abdutora', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos',
    equipamento: 'Máquina',
    descricao: '1. Sente com as pernas juntas nas almofadas internas.\n2. Abra as pernas contra a resistência da máquina.\n3. Esprema os abdutores e glúteos no final.\n4. Retorne lentamente.',
  },
  {
    id: 6013, nome: 'Agachamento Sumô', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Adutores, Glúteos',
    equipamento: 'Barra ou Halter',
    descricao: '1. Pés bem mais abertos que os ombros, dedos apontando para fora.\n2. Desça em agachamento mantendo o tronco ereto.\n3. Joelhos na mesma direção dos dedos.\n4. Sobe espremendo adutores e glúteos.',
  },
  {
    id: 6014, nome: 'Leg Press Unilateral', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos',
    equipamento: 'Máquina Leg Press',
    descricao: '1. Posicione apenas um pé no centro da plataforma.\n2. Execute o movimento com uma perna de cada vez.\n3. Corrige desequilíbrios entre as pernas.\n4. Controle total na descida.',
  },
  {
    id: 6015, nome: 'Agachamento Frontal com Barra', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Core, Ombros',
    equipamento: 'Barra',
    descricao: '1. Barra apoiada na frente dos ombros, cotovelos altos.\n2. Pés na largura dos ombros.\n3. Desça mantendo o tronco bem ereto.\n4. Maior ativação do quadríceps em relação ao agachamento convencional.',
  },
  {
    id: 6016, nome: 'Stiff Unilateral com Halter', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos, Lombar',
    equipamento: 'Halter',
    descricao: '1. Em pé em uma perna, segure o halter à frente do corpo.\n2. Incline o tronco para frente enquanto a perna livre se eleva atrás.\n3. Desça até sentir o posterior da perna de apoio esticar.\n4. Suba contraindo o glúteo e posterior.',
  },
  {
    id: 6017, nome: 'Stiff com Halteres', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos, Lombar',
    equipamento: 'Halteres',
    descricao: '1. Em pé com um halter em cada mão à frente das coxas.\n2. Pernas levemente dobradas, lombar neutra.\n3. Incline o tronco para frente empurrando o quadril para trás.\n4. Desça os halteres próximos às pernas sentindo o posterior esticar.\n5. Suba contraindo posterior e glúteos.',
  },
  {
    id: 6018, nome: 'Flexão de Joelhos em Pé (Máquina)', grupoMuscular: 'Pernas',
    musculosSecundarios: '',
    equipamento: 'Máquina',
    descricao: '1. Fique em pé na máquina com o tornozelo sob o apoio.\n2. Dobre o joelho puxando o calcanhar em direção ao glúteo.\n3. Esprema o posterior no topo.\n4. Desça lentamente.\n5. Ativação diferente da mesa flexora — trabalha o músculo em posição mais alongada.',
  },
  {
    id: 6019, nome: 'Agachamento no Smith', grupoMuscular: 'Pernas',
    musculosSecundarios: 'Glúteos, Core',
    equipamento: 'Smith',
    descricao: '1. Posicione a barra do Smith nos ombros.\n2. Pés um pouco à frente do alinhamento da barra.\n3. Desça até a coxa paralela ou abaixo.\n4. O Smith guia o movimento — boa opção para iniciantes ou lesionados.\n5. Suba empurrando o chão com os calcanhares.',
  },
  {
    id: 6020, nome: 'Cadeira Extensora Unilateral', grupoMuscular: 'Pernas',
    musculosSecundarios: '',
    equipamento: 'Máquina',
    descricao: '1. Sente na cadeira extensora e use apenas uma perna.\n2. Estenda até quase a extensão total.\n3. Segure 1 segundo espremendo o quadríceps.\n4. Retorne lentamente em 3–4 segundos.\n5. Corrige desequilíbrios entre as pernas.',
  },

  // ─── PANTURRILHA ─────────────────────────────────────────────────────────
  {
    id: 7001, nome: 'Panturrilha em Pé (Gêmeos)', grupoMuscular: 'Panturrilha',
    musculosSecundarios: '',
    equipamento: 'Máquina ou Halter',
    descricao: '1. Fique em pé com as pontas dos pés em uma plataforma elevada.\n2. Desça os calcanhares abaixo da plataforma para estirar o músculo.\n3. Suba na ponta dos pés o máximo possível.\n4. Segure 1 segundo no topo.\n5. Use pesos adicionais para progressão.',
  },
  {
    id: 7002, nome: 'Panturrilha Sentado (Sóleo)', grupoMuscular: 'Panturrilha',
    musculosSecundarios: '',
    equipamento: 'Máquina',
    descricao: '1. Sente na máquina com os joelhos a 90°.\n2. Pesos apoiados acima dos joelhos.\n3. Eleve os calcanhares na ponta dos pés.\n4. Segure no topo e desça controlando.\n5. Com os joelhos dobrados, o foco vai para o sóleo.',
  },
  {
    id: 7003, nome: 'Panturrilha no Leg Press', grupoMuscular: 'Panturrilha',
    musculosSecundarios: '',
    equipamento: 'Máquina Leg Press',
    descricao: '1. Posicione apenas as pontas dos pés na parte inferior da plataforma.\n2. Com as pernas quase estendidas, empurre a plataforma com as pontas dos pés.\n3. Esprema a panturrilha no topo.\n4. Retorne baixando os calcanhares além do nível neutro.',
  },
  {
    id: 7004, nome: 'Panturrilha Unilateral com Halter', grupoMuscular: 'Panturrilha',
    musculosSecundarios: '',
    equipamento: 'Halter, Degrau',
    descricao: '1. Fique em um pé só na borda de um degrau, segurando um halter.\n2. Desça o calcanhar abaixo do degrau.\n3. Suba na ponta do pé o máximo possível.\n4. Alternando os lados.',
  },
  {
    id: 7005, nome: 'Panturrilha no Smith', grupoMuscular: 'Panturrilha',
    musculosSecundarios: '',
    equipamento: 'Smith, Degrau',
    descricao: '1. Posicione as pontas dos pés em uma plataforma elevada sob o Smith.\n2. Barra apoiada nos ombros como no agachamento.\n3. Desça os calcanhares abaixo do nível dos pés.\n4. Suba na ponta dos pés o máximo possível, espremendo as panturrilhas.\n5. Permite carga maior que o halter unilateral.',
  },

  // ─── GLÚTEOS ─────────────────────────────────────────────────────────────
  {
    id: 8001, nome: 'Hip Thrust com Barra', grupoMuscular: 'Glúteos',
    musculosSecundarios: 'Posterior de coxa, Core',
    equipamento: 'Barra, Banco',
    descricao: '1. Apoie as escápulas em um banco com os pés no chão.\n2. Barra sobre o quadril (use almofada).\n3. Empurre o quadril para cima espremendo os glúteos.\n4. No topo, o tronco deve estar paralelo ao chão.\n5. Desça controlando sem tocar os glúteos no chão.',
  },
  {
    id: 8002, nome: 'Elevação Pélvica no Banco', grupoMuscular: 'Glúteos',
    musculosSecundarios: 'Posterior de coxa',
    equipamento: 'Banco',
    descricao: '1. Deite com as costas no chão, pés apoiados no banco.\n2. Eleve o quadril espremendo os glúteos no topo.\n3. Versão mais simples do Hip Thrust.\n4. Adicione peso sobre o quadril para progressão.',
  },
  {
    id: 8003, nome: 'Glúteo no Cabo (Kickback)', grupoMuscular: 'Glúteos',
    musculosSecundarios: 'Posterior de coxa',
    equipamento: 'Polia baixa',
    descricao: '1. Prenda a alça no tornozelo e ajuste a polia na posição baixa.\n2. Apoie-se na máquina ou em uma superfície firme.\n3. Empurre a perna para trás estendendo o quadril.\n4. Esprema o glúteo no final e retorne controlando.',
  },
  {
    id: 8004, nome: 'Agachamento Sumô com Halter', grupoMuscular: 'Glúteos',
    musculosSecundarios: 'Adutores, Pernas',
    equipamento: 'Halter ou Kettlebell',
    descricao: '1. Pés largos com dedos apontando para fora.\n2. Segure um halter verticalmente entre as pernas.\n3. Desça com o tronco ereto sentindo adutores e glúteos.\n4. Suba espremendo glúteos.',
  },
  {
    id: 8005, nome: 'Avanço com Passada Longa', grupoMuscular: 'Glúteos',
    musculosSecundarios: 'Pernas',
    equipamento: 'Peso corporal ou Halteres',
    descricao: '1. Dê um passo bem longo para frente.\n2. Desça profundamente até o joelho traseiro tocar o chão.\n3. Foco em empurrar com o calcanhar da frente para ativar mais o glúteo.\n4. Retorne e alterne os lados.',
  },
  {
    id: 8006, nome: 'Glúteo na Máquina (Extensão de Quadril)', grupoMuscular: 'Glúteos',
    musculosSecundarios: 'Posterior de coxa',
    equipamento: 'Máquina',
    descricao: '1. Posicione-se na máquina com o quadril na almofada.\n2. Empurre para trás estendendo o quadril o máximo possível.\n3. Esprema no final e retorne com controle.',
  },
  {
    id: 8007, nome: 'Hip Thrust com Halter', grupoMuscular: 'Glúteos',
    musculosSecundarios: 'Posterior de coxa',
    equipamento: 'Halter, Banco',
    descricao: '1. Apoie as escápulas em um banco com os pés no chão.\n2. Segure um halter sobre o quadril com as duas mãos.\n3. Empurre o quadril para cima espremendo os glúteos.\n4. No topo, o tronco deve estar paralelo ao chão.\n5. Versão mais acessível que a barra para iniciantes.',
  },
  {
    id: 8008, nome: 'Glúteo 4 Apoios na Polia', grupoMuscular: 'Glúteos',
    musculosSecundarios: 'Core',
    equipamento: 'Polia baixa',
    descricao: '1. Prenda a alça no tornozelo e ajuste a polia na posição baixa.\n2. Apoie-se em 4 apoios (mãos e joelhos) de costas para a máquina.\n3. Empurre a perna para cima e para trás estendendo o quadril.\n4. Esprema o glúteo no topo por 1 segundo.\n5. Retorne controlando sem tocar o joelho no chão.',
  },
  {
    id: 8009, nome: 'Abdução de Quadril no Cabo', grupoMuscular: 'Glúteos',
    musculosSecundarios: 'Abdutores',
    equipamento: 'Polia baixa',
    descricao: '1. Prenda a alça no tornozelo e fique de lado para a máquina.\n2. Mantendo a perna reta, abra lateralmente contra a resistência do cabo.\n3. Esprema o glúteo médio no final.\n4. Retorne com controle sem cruzar demais a perna.\n5. Trabalha o glúteo médio e mínimo.',
  },

  // ─── ABDÔMEN ─────────────────────────────────────────────────────────────
  {
    id: 9001, nome: 'Abdominal Crunch', grupoMuscular: 'Abdômen',
    musculosSecundarios: '',
    equipamento: 'Peso corporal',
    descricao: '1. Deite de costas com os joelhos dobrados.\n2. Mãos atrás da cabeça (sem puxar o pescoço).\n3. Contraia o abdômen levantando apenas os ombros do chão.\n4. Expire na subida.\n5. Não force o pescoço.',
  },
  {
    id: 9002, nome: 'Abdominal no Cabo', grupoMuscular: 'Abdômen',
    musculosSecundarios: '',
    equipamento: 'Polia alta, corda',
    descricao: '1. Ajoelhe-se de frente à polia alta com a corda.\n2. Segure a corda na altura da cabeça.\n3. Contraia o abdômen flexionando o tronco para baixo.\n4. Mantenha o quadril estático.\n5. Retorne de forma controlada.',
  },
  {
    id: 9003, nome: 'Elevação de Pernas', grupoMuscular: 'Abdômen',
    musculosSecundarios: 'Flexores do quadril',
    equipamento: 'Barra fixa ou banco',
    descricao: '1. Pendurado na barra ou apoiado nos cotovelos.\n2. Mantenha as pernas retas ou levemente dobradas.\n3. Eleve as pernas até 90° (ou mais).\n4. Desça de forma controlada sem balançar.',
  },
  {
    id: 9004, nome: 'Prancha (Plank)', grupoMuscular: 'Abdômen',
    musculosSecundarios: 'Core, Ombros',
    equipamento: 'Peso corporal',
    descricao: '1. Posição de apoio nos antebraços e pontas dos pés.\n2. Corpo alinhado da cabeça aos calcanhares.\n3. Core contraído, glúteos espremidos.\n4. Não deixe o quadril cair ou subir.\n5. Segure pelo tempo desejado.',
  },
  {
    id: 9005, nome: 'Oblíquo Russo (Russian Twist)', grupoMuscular: 'Abdômen',
    musculosSecundarios: 'Oblíquos',
    equipamento: 'Peso ou halter',
    descricao: '1. Sente no chão com os joelhos dobrados, tronco reclinado a 45°.\n2. Segure um peso com as duas mãos.\n3. Gire o tronco de lado a lado tocando o peso no chão.\n4. Para aumentar: levante os pés do chão.',
  },
  {
    id: 9006, nome: 'Mountain Climber', grupoMuscular: 'Abdômen',
    musculosSecundarios: 'Core, Cardio',
    equipamento: 'Peso corporal',
    descricao: '1. Posição de flexão de braço.\n2. Leve um joelho em direção ao peito rapidamente.\n3. Alterne as pernas em ritmo acelerado.\n4. Mantenha o core contraído e o quadril estável.',
  },
  {
    id: 9007, nome: 'Abdominal Infra (Elevação de Quadril)', grupoMuscular: 'Abdômen',
    musculosSecundarios: '',
    equipamento: 'Peso corporal',
    descricao: '1. Deite de costas com as pernas elevadas a 90°.\n2. Contraia o abdômen inferior elevando o quadril do chão.\n3. Retorne lentamente.\n4. O movimento é pequeno, foque na contração.',
  },
  {
    id: 9008, nome: 'Roda Abdominal (Ab Wheel)', grupoMuscular: 'Abdômen',
    musculosSecundarios: 'Core, Costas',
    equipamento: 'Roda abdominal',
    descricao: '1. Ajoelhe-se segurando a roda abdominal.\n2. Role para frente mantendo o core contraído.\n3. Vá até onde conseguir sem perder a forma.\n4. Puxe de volta usando o abdômen, não as costas.',
  },
  {
    id: 9009, nome: 'Abdominal Bicicleta', grupoMuscular: 'Abdômen',
    musculosSecundarios: 'Oblíquos',
    equipamento: 'Peso corporal',
    descricao: '1. Deite com as mãos atrás da cabeça e os pés elevados.\n2. Leve o cotovelo direito ao joelho esquerdo enquanto estende a perna direita.\n3. Alterne os lados em movimento contínuo de pedalada.\n4. Mantenha a lombar encostada no chão.\n5. Ótimo para oblíquos e reto abdominal.',
  },
  {
    id: 9010, nome: 'Crunch Reverso', grupoMuscular: 'Abdômen',
    musculosSecundarios: 'Flexores do quadril',
    equipamento: 'Peso corporal',
    descricao: '1. Deite de costas com as pernas elevadas a 90°.\n2. Contraindo o abdômen inferior, traga os joelhos em direção ao peito.\n3. Eleve levemente o quadril do chão.\n4. Retorne lentamente sem deixar os pés tocarem o chão.\n5. Foco no abdômen inferior.',
  },
  {
    id: 9011, nome: 'Prancha Lateral', grupoMuscular: 'Abdômen',
    musculosSecundarios: 'Oblíquos, Quadril',
    equipamento: 'Peso corporal',
    descricao: '1. Deite de lado apoiado no antebraço e no pé.\n2. Eleve o quadril formando uma linha reta do ombro ao pé.\n3. Core contraído, quadril sem cair.\n4. Segure pelo tempo desejado.\n5. Excelente para oblíquos e estabilidade lateral.',
  },

  // ─── ANTEBRAÇO ───────────────────────────────────────────────────────────
  {
    id: 10001, nome: 'Rosca de Pulso com Barra', grupoMuscular: 'Antebraço',
    musculosSecundarios: '',
    equipamento: 'Barra',
    descricao: '1. Sente em um banco com os antebraços apoiados nas coxas.\n2. Segure a barra com pegada supinada.\n3. Flexione os pulsos para cima o máximo possível.\n4. Desça de forma controlada.',
  },
  {
    id: 10002, nome: 'Rosca de Pulso Inversa', grupoMuscular: 'Antebraço',
    musculosSecundarios: '',
    equipamento: 'Barra',
    descricao: '1. Mesma posição da rosca de pulso normal.\n2. Pegada pronada (palmas para baixo).\n3. Eleve os pulsos para cima contra a resistência.\n4. Trabalha o lado extensor do antebraço.',
  },
  {
    id: 10003, nome: 'Farmer Walk (Caminhada com Peso)', grupoMuscular: 'Antebraço',
    musculosSecundarios: 'Trapézio, Core',
    equipamento: 'Halteres pesados',
    descricao: '1. Segure halteres pesados em cada mão ao lado do corpo.\n2. Caminhe por uma distância determinada mantendo postura ereta.\n3. Core contraído, ombros para trás.\n4. Ótimo para força de pegada e funcional.',
  },

  // ─── CARDIO / FUNCIONAIS ─────────────────────────────────────────────────
  {
    id: 11001, nome: 'Esteira', grupoMuscular: 'Cardio',
    musculosSecundarios: 'Pernas',
    equipamento: 'Esteira',
    descricao: 'Configure velocidade e inclinação conforme seu objetivo:\n• Aquecimento: 5 km/h por 5 min\n• Moderado: 7–9 km/h\n• Intenso: 10–12 km/h ou inclinação acima de 5°\n• HIIT: alterne 1 min rápido / 1 min lento',
  },
  {
    id: 11002, nome: 'Bicicleta Ergométrica', grupoMuscular: 'Cardio',
    musculosSecundarios: 'Pernas',
    equipamento: 'Bicicleta ergométrica',
    descricao: 'Ajuste o banco para que os joelhos fiquem levemente dobrados no ponto mais baixo.\n• Resistência baixa = aeróbico leve\n• Resistência alta = força e potência\n• Cadência recomendada: 70–90 RPM',
  },
  {
    id: 11003, nome: 'Elíptico', grupoMuscular: 'Cardio',
    musculosSecundarios: 'Pernas, Braços',
    equipamento: 'Elíptico',
    descricao: 'Exercício de baixo impacto para articulações.\n• Excelente para quem tem dores nos joelhos.\n• Use os braços ativamente.\n• Varie resistência e velocidade para intensidade.',
  },
  {
    id: 11004, nome: 'Remo Ergométrico', grupoMuscular: 'Cardio',
    musculosSecundarios: 'Costas, Pernas, Core',
    equipamento: 'Remo ergométrico',
    descricao: '1. Pés presos no suporte, posição inicial com joelhos dobrados.\n2. Empurre com as pernas, incline o tronco para trás e puxe o remo ao abdômen.\n3. Retorne na ordem inversa: braços, tronco, pernas.\n4. Frequência: 18–24 remadas por minuto.',
  },
  {
    id: 11005, nome: 'Corda de Pular', grupoMuscular: 'Cardio',
    musculosSecundarios: 'Panturrilha, Ombros',
    equipamento: 'Corda',
    descricao: '• Fique nos dedos dos pés com os joelhos levemente dobrados.\n• Gire a corda pelos pulsos, não pelos braços.\n• Comece com 30 seg e aumente progressivamente.\n• Ótimo para coordenação e condicionamento.',
  },
  {
    id: 11006, nome: 'Burpee', grupoMuscular: 'Cardio',
    musculosSecundarios: 'Corpo inteiro',
    equipamento: 'Peso corporal',
    descricao: '1. Em pé, desça em agachamento e apoie as mãos no chão.\n2. Salte os pés para trás, chegando em posição de flexão.\n3. Faça uma flexão (opcional).\n4. Salte os pés de volta e suba em salto com os braços acima da cabeça.',
  },
  {
    id: 11007, nome: 'Kettlebell Swing', grupoMuscular: 'Cardio',
    musculosSecundarios: 'Glúteos, Posterior de coxa, Core',
    equipamento: 'Kettlebell',
    descricao: '1. Pés na largura dos ombros, kettlebell entre os pés.\n2. Pegue com as duas mãos, incline o tronco e impulsione com o quadril.\n3. Deixe o kettlebell balançar até a altura dos ombros.\n4. Retorne com controle curvando o quadril (não a lombar).',
  },

];

export const GRUPOS_MUSCULARES = [
  'Peito',
  'Costas',
  'Ombros',
  'Bíceps',
  'Tríceps',
  'Pernas',
  'Panturrilha',
  'Glúteos',
  'Abdômen',
  'Antebraço',
  'Cardio',
];
